// react/src/ai-components/gantt/progress/progress.tsx
import { GanttComponent, Toolbar, Edit, Selection, Sort, Reorder, ContextMenu, DayMarkers, Inject, ColumnDirective, ColumnsDirective } from '@syncfusion/ej2-react-gantt';
import { TaskDataCollection } from './datasource';
import * as data from './progress.json';
import { getAzureChatAIRequest } from '../../../ai-models';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';

function Progress() {
    let ganttInstance: GanttComponent;
    const taskFields = {
        id: 'TaskID',
        name: 'TaskName',
        startDate: 'StartDate',
        endDate: 'EndDate',
        duration: 'Duration',
        progress: 'Progress',
        parentID: "ParentTaskID"
    };
    const toolbarTemplate = () => {
        return <ButtonComponent id='toolbarButton' isPrimary={true}>Predict milestone</ButtonComponent>
    }

    const toolbarOptions = [{
        template: toolbarTemplate, text: 'Predict milestone'
    }]

    function toolbarClick(args: any) {
        if (args.item.text === 'Predict milestone') {
            ganttInstance.showSpinner();
            let input =
                "You analyze the multiple year HistoricalTaskDataCollections and current TaskDataCollection to predict project completion dates and milestones based on current progress and historical trends. Ignore the null or empty values, and collection values based parent child mapping. Avoid json tags with your response. No other explanation or content to be returned." +
                " HistoricalTaskDataCollections :" + getHistoricalCollection() +
                " TaskDataCollection: " + JSON.stringify(TaskDataCollection) +
                " Generate a JSON object named 'TaskDetails' containing:" +
                "- Key 'MilestoneTaskDate' with a list of milestone dates 'MilestoneDate' with 'TaskName' - task name. A milestone date is defined as the end date of tasks with a duration of 0 and only give current based milestone." +
                "- Key 'ProjectCompletionDate' indicating the latest end date among all tasks." +
                "- Key 'Summary' providing a summary of the project completion date and milestones.Ensure milestones are defined correctly based on tasks with a duration of 0, and the project completion date reflects the latest end date of all tasks "
            let aioutput = getAzureChatAIRequest({ messages: [{ role: 'user', content: input }] });
            aioutput.then((result: any) => {
                let cleanedJsonData = result.replace(/^```json\n|```\n?$/g, '');
                let dataset = JSON.parse(cleanedJsonData);
                const eventMarkers = dataset.TaskDetails.MilestoneTaskDate
                    .map((milestone: any) => ({
                        day: new Date(milestone["MilestoneDate"]),
                        label: milestone["TaskName"]
                    }));
                let projectDetailes = {
                    day: new Date(dataset.TaskDetails.ProjectCompletionDate),
                    label: "Project completion date"
                }
                eventMarkers.push(projectDetailes)
                ganttInstance.eventMarkers = eventMarkers;
                ganttInstance.hideSpinner();
            });
        }
        function getHistoricalCollection() {
            let historicalDataCollection: string = '';
            const word: any = data;
            for (let year = 2021; year < 2026; year++) {
                historicalDataCollection += "HistoricalTaskDataCollection" + year + ":" + JSON.stringify(word["TaskDataCollection" + year]);
            }
            return historicalDataCollection;
        }
    }

    return (
        <div className='control-pane'>
            <div className='control-section'>
                <div className="description-container e-card">
                    <div className='e-card-content '>
                        <p>This sample uses AI to predict milestone dates and the overall project completion date. The predictions are based on the current year's TaskCollection data, along with an analysis of historical data from the past five years. Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/gantt/Readme.md">here</a>.</p>
                    </div>
                </div>
                <div id='container'>
                    <GanttComponent
                        ref={(gantt: GanttComponent) => ganttInstance = gantt as GanttComponent}
                        dataSource={TaskDataCollection}
                        enableContextMenu={true}
                        allowSorting={true}
                        allowReordering={true}
                        taskFields={taskFields}
                        editSettings={{
                            allowAdding: true,
                            allowEditing: true,
                            allowDeleting: true,
                            allowTaskbarEditing: true,
                            showDeleteConfirmDialog: true
                        }}
                        toolbar={toolbarOptions}
                        toolbarClick={toolbarClick}
                        splitterSettings={{
                            position: "28%"
                        }}
                        allowSelection={true}
                        treeColumnIndex={1}
                        height='550px'
                        projectStartDate={new Date('4/1/2026')}
                        projectEndDate={new Date('6/2/2026')}
                    >
                        <ColumnsDirective>
                            <ColumnDirective field='TaskID' visible={false} />
                            <ColumnDirective field='TaskName' headerText='Event Name' width={250} />
                            <ColumnDirective field='Duration' />
                            <ColumnDirective field='StartDate' headerText='Start Date' />
                            <ColumnDirective field='EndDate' headerText='End Date' />
                        </ColumnsDirective>
                        <Inject services={[Edit, Toolbar, Selection, DayMarkers, Sort, Reorder, ContextMenu]} />
                    </GanttComponent>
                </div>
            </div>
        </div>
    )
}

export default Progress;

// angular/src/app/gantt/progress/progress.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { TaskDataCollection } from './ganttdata';
import { getAzureChatAIRequest } from '../../ai-models/ai-models'; 
import * as data from './progress.json';
import { ToolbarModule } from '@syncfusion/ej2-angular-navigations'
import { ToolbarService } from '@syncfusion/ej2-angular-gantt'
import { GanttAllModule } from '@syncfusion/ej2-angular-gantt';

@Component({
  selector: 'app-progress',
  standalone: true,
  imports: [GanttAllModule,ToolbarModule],
  providers: [ToolbarService],
  templateUrl: './progress.component.html',
  styleUrl: './progress.component.css'
})
export class ProgressComponent {
  @ViewChild('ganttDefault', { static: false }) gantt!: ElementRef;
  public data?: object[];
  public taskSettings?: object;
  public editSetting?:object;
  public splitterSettings?:object;
  public toolbar?:object[];
  public projectStartDate= new Date('4/1/2026');
  public projectEndDate= new Date('6/2/2026');
  ngOnInit(): void {
    this.data = TaskDataCollection;
    this.taskSettings = {
      id: 'TaskID',
      name: 'TaskName',
      startDate: 'StartDate',
      endDate: 'EndDate',
      duration: 'Duration',
      progress: 'Progress',
      parentID: "ParentTaskID"
  };
    this.editSetting = {
      allowAdding: true,
      allowEditing: true,
      allowDeleting: true,
      allowTaskbarEditing: true,
      showDeleteConfirmDialog: true
  };
    this.splitterSettings = {
      position: "28%"
  };
    this.toolbar = [{template: '<button id="toolbarButton" class="e-btn e-primary">Predict milestone</button>', text:'Predict milestone' }];
  }

  public toolbarClick(args: any) {
    debugger
    if (args.item.text === 'Predict milestone') {
      console.log( (this.gantt as any).ganttProperties);
      (this.gantt as any).showSpinner();
        let input =
            "You analyze the multiple year HistoricalTaskDataCollections and current TaskDataCollection to predict project completion dates and milestones based on current progress and historical trends. Ignore the null or empty values, and collection values based parent child mapping. Avoid json tags with your response. No other explanation or content to be returned." +
            " HistoricalTaskDataCollections :" + getHistoricalCollection() +
            " TaskDataCollection: " + JSON.stringify(TaskDataCollection) +
            " Generate a JSON object named 'TaskDetails' containing:" +
            "- Key 'MilestoneTaskDate' with a list of milestone dates 'MilestoneDate' with 'TaskName' - task name. A milestone date is defined as the end date of tasks with a duration of 0 and only give current based milestone." +
            "- Key 'ProjectCompletionDate' indicating the latest end date among all tasks." +
            "- Key 'Summary' providing a summary of the project completion date and milestones.Ensure milestones are defined correctly based on tasks with a duration of 0, and the project completion date reflects the latest end date of all tasks "
        let aioutput = getAzureChatAIRequest({ messages: [{ role: 'user', content: input }] });
        aioutput.then((result: any) => {
            let cleanedJsonData: string = result.replace(/^```json\n|```\n?$/g, '');
            let dataset: any = JSON.parse(cleanedJsonData);
            let details = dataset.TaskDetails || dataset;
            let eventMarkers: any = details.MilestoneTaskDate
                .map((milestone: any) => ({
                    day: new Date(milestone["MilestoneDate"]),
                    label: milestone["TaskName"]
                }));
            let projectDetails = {
                day: new Date(details.ProjectCompletionDate),
                label: "Project completion date"
            };
            eventMarkers.push(projectDetails);
            (this.gantt as any).eventMarkers = eventMarkers;

            (this.gantt as any).hideSpinner();
        });
    }
    function getHistoricalCollection(): string {
        let historicalDataCollection: string = '';
        const word = (<any>data);
        for (let year = 2021; year < 2026; year++) {
            historicalDataCollection += "HistoricalTaskDataCollection" + year + ":" + JSON.stringify(word["TaskDataCollection" + year]);
        }

        return historicalDataCollection;
    }
}
}

<h2 style="text-align: center;">Smart Progress Prediction</h2>
    <div class="description-container e-card">
        <div class='e-card-content '>
            <!--!-->
            <p>
                This sample demonstrates how AI-driven analysis predicts milestone task completion and project end dates within a Gantt Chart. Predictions are shown as event markers, offering visual cues for upcoming milestones and the overall project timeline.
            </p>
        </div>
    </div>
    <div id='container'>
        <ejs-gantt #ganttDefault height="430px" [dataSource]="data" [taskFields]="taskSettings"  [editSettings]="editSetting"
        [allowSorting]="true" [allowReordering]="true" [allowSelection]="true" [treeColumnIndex]="1" [enableContextMenu]="true"
       [splitterSettings]="splitterSettings" [toolbar]="toolbar" (toolbarClick)="toolbarClick($event)" [projectStartDate]="projectStartDate" [projectEndDate]="projectEndDate">
        <e-columns>
            <e-column field='TaskID' headerText='Task ID' [visible]="false"></e-column>
            <e-column field='TaskName' headerText='Event Name' [width]="250"></e-column>
            <e-column field='Duration' ></e-column>
            <e-column field='StartDate' headerText='Start Date' ></e-column>
            <e-column field='EndDate' headerText='End Date'></e-column>
        </e-columns> 
        </ejs-gantt>
    <div id="csfooter" style="width: 100%; height: 66px; background-color: #F0FFFF;min-height: 120px; padding: 15px;"></div>
</div>
