// angular/src/app/grid/assistive-grid/frontend/assistive-grid.component.ts
import { Component, ViewChild, TemplateRef, Inject, ElementRef, Renderer2 } from '@angular/core';
import { GridAllModule, GridComponent, ToolbarService, SortService, FilterService, GroupService, PageService, FilterSettingsModel } from '@syncfusion/ej2-angular-grids';
import { AIAssistViewComponent, AIAssistViewModule, PromptRequestEventArgs, ToolbarSettingsModel } from '@syncfusion/ej2-angular-interactive-chat';
import { DialogComponent, DialogModule } from '@syncfusion/ej2-angular-popups';
import { purchaseDetails } from './datasource';
import { fetchAI } from '../model/ai-input';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-assistive-grid',
  imports: [GridAllModule, AIAssistViewModule, DialogModule, CommonModule],
  providers: [ToolbarService, SortService, FilterService, GroupService, PageService],
  templateUrl: './assistive-grid.component.html',
  styleUrl: './assistive-grid.component.css',
  standalone: true
})
export class AssistiveGridComponent {
  @ViewChild('grid') grid!: GridComponent;
  @ViewChild('dialog') dialog!: DialogComponent;
  @ViewChild('assistView') assistView!: AIAssistViewComponent;

  public data = purchaseDetails;

  public pageSettings = { pageSize: 12 };

  public filterSettings: FilterSettingsModel = { type: 'Excel' };

  public toolbarOptions: any = [
    { text: 'AI Assist', tooltipText: 'AI Assist', prefixIcon: 'e-assistview-icon', id: 'ai-assist-btn', align: 'Right' }
  ];

  constructor(private renderer: Renderer2) {}

  public toolbarSettings: ToolbarSettingsModel = {
    items: [
      { tooltip: 'Start New Chat', iconCss: 'e-icons e-rename', align: 'Right' },
      { tooltip: 'Clear', iconCss: 'e-icons e-refresh', align: 'Right' },
      { tooltip: 'Close', iconCss: 'e-icons e-icon-dlg-close', align: 'Right' }
    ],
    itemClicked: (args: any): void => {
    if (args.item.iconCss.includes('e-icon-dlg-close')) {
      this.dialog.hide();
    }
    if (args.item.iconCss.includes('e-rename')) {
      this.assistView.prompts = [];
    }
    if (args.item.iconCss.includes('e-refresh')) {
      this.assistView.prompts = [];
      this.grid.sortSettings = { columns: [] };
      this.grid.filterSettings = { columns: [] };
      this.grid.groupSettings = { columns: [] };
      this.grid.pageSettings = { pageSize: 12, currentPage: 1 };
      this.grid.refresh();
    }
  }
  };

  public suggestions: string[] = [
    "Filter iPhone 15 Pro",
    "Sort Amount from lowest to highest",
    "Payment status completed",
    "Group status column",
    "Clear Filtering",
    "Clear Sorting",
    "Remove Grouping"
  ];

  private clickListener!: () => void;

  ngAfterViewInit(): void {
    // Listen for clicks on the entire document
    this.clickListener = this.renderer.listen('document', 'mousedown', (event: MouseEvent) => {
      if (!this.dialog?.visible) return;
      const dialogElement = document.getElementById('ai-assist-dialog');
      if (dialogElement && !dialogElement.contains(event.target as Node)) {
        const clickedOnToolbarBtn = (event.target as HTMLElement)?.closest('#ai-grid_toolbar_ai-assist-btn');
        if (!clickedOnToolbarBtn) {
          this.dialog.hide();
        }
      }
    });
  }

  ngOnDestroy(): void {
    if (this.clickListener) {
      this.clickListener();
    }
  }

  // Toolbar click handler
  toolbarClick = (args: any) => {
        if (args.item.id === 'ai-assist-btn') {
            const gridRect = this.grid.element.getBoundingClientRect();
            const toolbarRect = document.getElementById('ai-grid_toolbarItems')!.getBoundingClientRect();
            const targetRect = (args.originalEvent.target as HTMLElement).closest('.e-toolbar-item')!.getBoundingClientRect();
            const x = targetRect.left - gridRect.left - (parseInt(this.dialog.width.toString()));
            const y = (toolbarRect.top + toolbarRect.height) - gridRect.top;
            this.dialog.position = { X: x, Y: y };
            this.dialog.show();
        }
    }

  // AI Prompt Request
  onPromptRequest(args: PromptRequestEventArgs): void {
    this.assistView.scrollToBottom();
    const columns = (this.grid.columns as any[])
      .map((col: any) => col.field)
      .filter(field => field);
    fetchAI(args.prompt, this.grid, this.assistView, columns);
  }

  // Response template function
  responseTemplate(props: any): string {
    return `
      <div class="response-item-content">
        <div class="response-header">
          <span class="e-icons e-assistview-icon"></span>
          ${props.response}
        </div>
      </div>
    `;
  }

  // Suggestion item click
  onSuggestionClick(text: string): void {
    this.assistView.executePrompt(text);
  }
}
<h2 style="text-align: center;">Assistive Grid</h2>
<div class="description-container e-card">
    <div class='e-card-content '>
        <!--!-->
        <p>
            This demo showcases the Syncfusion Angular DataGrid component, enhanced with conversational capabilities
            through the integrated Syncfusion Angular AI AssistView component. Grid data operations, such as sorting,
            filtering, and grouping, can be performed using natural language input, offering a streamlined alternative
            to traditional UI interactions.
        </p>
    </div>
</div>

<div id='container'>
    <div id="assistive-grid">
        <ejs-dialog #dialog id="ai-assist-dialog" target="#ai-grid" width="500px" height="500px" [visible]="false"
            [position]="{ X: 0, Y: 0 }" [footerTemplate]="footerTemplate">
            <div id="ai-grid-aiassistview" ejs-aiassistview #assistView [toolbarSettings]="toolbarSettings"
                (promptRequest)="onPromptRequest($event)" promptSuggestionsHeader="Suggestions"
                [responseItemTemplate]="responseItemTemplate">
                <e-views>
                    <e-view type="Assist" name="Ask AI"></e-view>
                </e-views>
            </div>
        </ejs-dialog>
        <ejs-grid #grid id="ai-grid" [dataSource]="data" height="860" [allowFiltering]="true" [allowSorting]="true"
            [allowPaging]="true" [allowGrouping]="true" [pageSettings]="pageSettings" [filterSettings]="filterSettings"
            [toolbar]="toolbarOptions" (toolbarClick)="toolbarClick($event)">
            <e-columns>
                <e-column field="TransactionID" headerText="Transaction ID" width="160"></e-column>
                <e-column field="CustomerName" headerText="Customer Name" width="220" textAlign="Center">
                    <ng-template #template let-data>
                        <div>
                            <p>{{data.CustomerName}}</p>
                            <p class="email">{{data.Email}}</p>
                        </div>
                    </ng-template>
                </e-column>
                <e-column field="ProductName" headerText="Product" width="208" textAlign="Left">
                    <ng-template #template let-data>
                        <div class="product-items">
                            <img class="rounded"
                                [src]="'../images/sales-transactions-table/' + data.ProductImage" width="40"
                                height="40" alt="product image" />
                            <p>{{data.ProductName}}</p>
                        </div>
                    </ng-template>
                </e-column>
                <e-column field="Quantity" headerText="Quantity" width="140" textAlign="Right"></e-column>
                <e-column field="Amount" headerText="Amount" width="130" format="c2" textAlign="Right"></e-column>
                <e-column field="PurchaseDate" headerText="Purchase Date" width="180" format="MM/dd/yyyy"
                    textAlign="Right"></e-column>
                <e-column field="PaymentMethod" headerText="Payment Method" width="200"></e-column>
                <e-column field="Status" headerText="Status" width="120" textAlign="Right">
                    <ng-template #template let-data>
                        <div>
                            <span [class]="'e-badge !px-2 ' + 
              (data.Status === 'Completed' ? 'e-badge-success' : 
               data.Status === 'Pending' ? 'e-badge-info' : 
               data.Status === 'Processing' ? 'e-badge-warning' : 
               data.Status === 'Failed' ? 'e-badge-danger' : '')">
                                {{data.Status}}
                            </span>
                        </div>
                    </ng-template>
                </e-column>
            </e-columns>
        </ejs-grid>
    </div>
    <ng-template #footerTemplate>
        <div class="e-suggestions">
            <div class="e-suggestion-header">Suggestions</div>
            <div class="e-suggestion-list">
                <ul>
                    <li *ngFor="let suggestion of suggestions" (click)="onSuggestionClick(suggestion)">
                        {{suggestion}}
                    </li>
                </ul>
            </div>
        </div>
    </ng-template>
    <ng-template #responseItemTemplate let-data>
        <div class="response-item-content">
            <div class="response-header">
                <span class="e-icons e-assistview-icon"></span>
            </div>
            <div class="assist-response-content" [innerHTML]='data.response'></div>
        </div>
    </ng-template>
</div>

// react/src/ai-components/grid/assistive-grid/frontend/assistive-grid.tsx
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { GridComponent, ColumnsDirective, ColumnDirective, Inject, Toolbar, Sort, Filter, Group, Page, Search, ToolbarItems, FilterSettingsModel, ColumnModel } from '@syncfusion/ej2-react-grids';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { AIAssistViewComponent, ToolbarSettingsModel, PromptRequestEventArgs, ViewsDirective, ViewDirective } from '@syncfusion/ej2-react-interactive-chat';
import { purchaseDetails, PurchaseDetailsArgs } from './datasource';
import { createRef } from "react";
import { fetchAI } from '../model/ai-input';
import { useEffect } from "react";
import './assistive-grid.css';
import { ClickEventArgs } from '@syncfusion/ej2-navigations';

let assistView!: AIAssistViewComponent;
let dialog!: DialogComponent;
let grid!: GridComponent;
let suggestionListRef = createRef<any>();

function AssistiveGrid() {

    // Toolbar options for Grid with AI Assist button.
    const toolbarOptions: object[] = [{text: 'AI Assist', tooltipText: 'AI Assist', prefixIcon: 'e-assistview-icon', id: 'ai-assist-btn', align: 'Right' }];

    // Handles the Grid toolbar button click action. If the AI Assist button clicked shows the AI Assist dialog.
    const toolbarClick = (args: ClickEventArgs) => {
        if (args.item.id === 'ai-assist-btn') {
            const gridRect = grid.element.getBoundingClientRect();
            const toolbarRect = document.getElementById('ai-grid_toolbarItems')!.getBoundingClientRect();
            const targetRect = (args.originalEvent.target as HTMLElement).closest('.e-toolbar-item')!.getBoundingClientRect();
            const x = targetRect.left - gridRect.left - (parseInt(dialog.width.toString()));
            const y = (toolbarRect.top + toolbarRect.height) - gridRect.top;
            dialog.position = { X: x, Y: y };
            dialog.show();
        }
    }

    // Configures toolbar settings for AI assist dialog.
    const toolbarSettings: ToolbarSettingsModel = {
        items: [
            { tooltip: 'Start New Chat', iconCss: 'e-icons e-rename', align: 'Right' },
            { tooltip: 'Clear', iconCss: 'e-icons e-refresh', align: 'Right' },
            { tooltip: 'Close', iconCss: 'e-icons e-icon-dlg-close', align: 'Right' },
        ],
        itemClicked: (args) => {
            if (args.item.iconCss === 'e-icons e-icon-dlg-close') {
                dialog.hide()
            }
            if (args.item.iconCss === 'e-icons e-rename') {
                assistView.prompts = [];
            }
            if (args.item.iconCss === 'e-icons e-refresh') {
                assistView.prompts = [];
                grid.setProperties({
                    sortSettings: { columns: [] },
                    filterSettings: { columns: [] },
                    groupSettings: { columns: [] },
                    pageSettings: { currentPage: 1, pageSize: 12 }
                });
                grid.refresh();
            }
        }
    };

    // Renders response template for AI prompts.
    const responseTemplate = (props: { prompt: string, response: string }) => {
        return (
            <div className="response-item-content">
                <div className="response-header">
                    <span className="e-icons e-assistview-icon"></span>
                    {props.response}
                </div>
            </div>
        );
    };

    // Handles prompt request execution.
    const onPromptRequest = (args: PromptRequestEventArgs) => {
        assistView.scrollToBottom();
        const columns = grid.columns.map((col: any) => { return { field: col.field } });
        columns.forEach((col: { field: string, values?: string[] }) => {
            if (col.field === 'status') {
                col.values = ['Completed', 'Pending', 'Failed', 'Processing'];
            }
            else if (col.field === 'paymentMethod') {
                col.values = ['Cheque', 'Credit Card', 'Paypal', 'Online Transfer'];
            }
        })
        fetchAI(args.prompt, grid, assistView, columns);
    };

    useEffect(() => {
        const handleMouseDown = (event: MouseEvent) => {
            if (!dialog.visible) return;
            const dialogElement = document.querySelector('#ai-assist-dialog.e-dialog');
            if (dialogElement && !dialogElement.contains(event.target as Node)) {
                dialog.hide();
            }
        };
        document.addEventListener('mousedown', handleMouseDown);
        return () => document.removeEventListener('mousedown', handleMouseDown);
    }, []);

    const suggestions = ["Filter iPhone 15 Pro", "Sort Amount from lowest to highest", "Filter Payment status completed",  "Group status column", "Clear Filtering", "Clear Sorting", "Remove Grouping"];

    // Renders footer template with suggestion list.
    const dialogFooterTemplate = () => {
        const handleClick = (text: string) => {
            assistView.executePrompt(text);
        };
        return (
            <div className="e-suggestions">
                <div className="e-suggestion-header">Suggestions</div>
                <div className="e-suggestion-list">
                    <ul ref={suggestionListRef}>
                        {suggestions.map((suggestion, index) => (
                        <li key={index} onClick={() => handleClick(suggestion)}>
                            {suggestion}
                        </li>
                        ))}
                    </ul>
                </div>
            </div>
        );
    }

    const filterSettings: FilterSettingsModel = { type: 'Excel' };

    return (
        <div>
            <div id='assistive-grid'>
                <DialogComponent ref={(dialogIns: DialogComponent) => dialog = dialogIns as DialogComponent} target='#ai-grid' id='ai-assist-dialog' width='500px' visible={false} height='500px' footerTemplate={dialogFooterTemplate}>
                    <AIAssistViewComponent id="ai-grid-aiassistview" ref={(assist: AIAssistViewComponent) => assistView = assist as AIAssistViewComponent} toolbarSettings={toolbarSettings} promptRequest={onPromptRequest} promptSuggestionsHeader='Suggestions' responseItemTemplate={responseTemplate} >
                        <ViewsDirective>
                            <ViewDirective type='Assist' name=' Ask AI'></ViewDirective>
                        </ViewsDirective>
                    </AIAssistViewComponent>
                </DialogComponent>
                <GridComponent ref={(gridIns: GridComponent) => grid = gridIns as GridComponent} id="ai-grid" height={650} dataSource={purchaseDetails} allowFiltering={true} allowSorting={true} allowGrouping={true} filterSettings={filterSettings} allowPaging={true} toolbar={toolbarOptions} toolbarClick={toolbarClick} >
                    <ColumnsDirective>
                        <ColumnDirective field="TransactionID" headerText="Transaction ID" width="160"
                        />
                        <ColumnDirective field="CustomerName" headerText="Customer Name" width="220" textAlign="Center"
                            template={(data: PurchaseDetailsArgs) => (
                                <div >
                                    <p>{data.CustomerName}</p>
                                    <p className="email">{data.Email}</p>
                                </div>
                            )} />
                        <ColumnDirective field="ProductName" headerText="Product" width="208" textAlign="Left"
                            template={(data: PurchaseDetailsArgs) => (
                                <div className='product-items'>
                                    <img className="rounded" src={`src/ai-components/grid/assistive-grid/images/sales-transactions-table/${data.ProductImage}`} width={40} height={40} alt="product image" />
                                    <p>{data.ProductName}</p>
                                </div>
                            )}
                        />
                        <ColumnDirective field="Quantity" headerText="Quantity" width="140" textAlign="Right" />
                        <ColumnDirective field="Amount" headerText="Amount" width="130" format="c2" textAlign="Right" />
                        <ColumnDirective field="PurchaseDate" headerText="Purchase Date" width="180" format={{ type: "date", format: "MM/dd/yyyy" }} textAlign="Right" />
                        <ColumnDirective field="PaymentMethod" headerText="Payment Method" width="200" />
                        <ColumnDirective field="Status" headerText="Status" width="120" textAlign='Right'
                            template={(data: PurchaseDetailsArgs) => (
                                <div >
                                    <span className={`e-badge ${data.Status === "Completed" ? "e-badge-success" : data.Status === "Pending" ? "e-badge-info" : data.Status === "Processing" ? "e-badge-warning" : data.Status === "Failed" ? "e-badge-danger" : ""} !px-2`}>{data.Status}</span>
                                </div>
                            )}
                        />
                    </ColumnsDirective>
                    <Inject services={[Toolbar, Sort, Filter, Group, Page]} />
                </GridComponent>
            </div>
        </div>
    )
}

export { AssistiveGrid };
