// angular/src/app/grid/semantic-search/semantic-search.component.ts
import { Component, ViewChild, TemplateRef } from '@angular/core';
import { TextBoxComponent, TextBoxModule } from '@syncfusion/ej2-angular-inputs';
import { GridAllModule, QueryCellInfoEventArgs, GridComponent } from '@syncfusion/ej2-angular-grids';
import { MedicalRecord, MedicalRecords } from './data';
import { cosineSimilarity } from "../../utils/cosine-similarity";
import { Query, Predicate } from "@syncfusion/ej2-data";
import { embeddingModel } from '../../ai-models/embedding-model';
import { Text } from 'openai/resources/beta/threads/messages.mjs';
@Component({
  selector: 'app-semantic-search',
  standalone: true,
  imports: [GridAllModule, TextBoxModule],
  templateUrl: './semantic-search.component.html',
  styleUrl: './semantic-search.component.css'
})
export class SemanticSearchComponent {
  @ViewChild('grid', { static: true }) grid!: GridComponent;
  @ViewChild('textbox', { static: true }) textbox!: TextBoxComponent;
  @ViewChild('toolbarTemplate', { static: true }) toolbarTemplate!: TemplateRef<any>;
  public machineDataList: MedicalRecord[] = MedicalRecords
  public toolbar: any;
  public productEmbeddings: { [key: string]: number[] } = {};
  public customizeCell(args: QueryCellInfoEventArgs): void {
    // Customize cell logic here
  }
  
  
  ngOnInit () {
    this.toolbar = [{ template: this.toolbarTemplate }];
  }
  generatePredicate(filteredData: MedicalRecord[]) {
    let predicates: Predicate[] = [];
    for (let i: number = 0; i < filteredData.length; i++) {
      predicates.push(new Predicate('Symptoms', 'contains', filteredData[i].Symptoms));
    }
    return Predicate.or(predicates);
  }
  async getEmbeddingsData() {
    for (let record of MedicalRecords) {
      let data: number[] = (await embeddingModel(
        record.DoctorDetails + ' ' + record.PatientID + ' ' + record.Symptoms + ' ' + record.Diagnosis
      )) as number[];
      this.productEmbeddings[record.RecordID] = data;
    }
  }
  async ExecutePrompt(searchValue: string) {
    let queryVector: any = await embeddingModel(searchValue);
    const similarityThreshold: number = 0.8;
    const outputData = MedicalRecords.filter((record: any) => {
      const similarity = cosineSimilarity(
        this.productEmbeddings[record.RecordID],
        queryVector
      );
      if (similarity > similarityThreshold) {
        return record;
      }
    });
    this.grid.hideSpinner();
    if (outputData.length > 0) {
      this.grid.query = new Query().where(this.generatePredicate(outputData));
    } else {
      this.grid.query = new Query().take(0);
    }
  }
  public created(): void {
    this.getEmbeddingsData();
  }

  smartSearch() {
 
    let searchEle: HTMLInputElement = this.grid.element.querySelector('#semantic-grid input.e-textbox')!;
      if (searchEle) {
        let searchValue: string = searchEle.value.trim();
        if (searchValue) {
          this.grid.showSpinner();
          this.ExecutePrompt(searchValue);
        } else {
          this.grid.query = new Query();
        }

      }
    
  }
}

<h2 style="text-align: center;">Semantic Filtering</h2>
<div class="description-container e-card">
    <div class='e-card-content '>
        <!--!-->
        <p>
            This example shows how the DataGrid presents medical report data. Using Semantic Search, you can find relevant information without needing to use the exact terms. For instance, searching for "stomach" will still bring up reports about "Abdominal pain." The grid updates search results dynamically using local embeddings.  
        </p>
    </div>
</div>
<div id='container'>
    <ejs-grid #grid 
    id="semantic-grid"
    [dataSource]='machineDataList'
    [toolbar]='toolbar'
    (queryCellInfo)='customizeCell($event)'
    [enableHover]='false'
    [enableStickyHeader]='true'
    [allowTextWrap]='true'
    [enableAltRow]='true'
    (created)='created()'
    [rowHeight]='75'
    [height]='450'
    >
        <e-columns>
            <e-column field="RecordID" headerText="Record ID" textAlign="Right" width="90"></e-column>
            <e-column field="PatientID" headerText="Patient ID" textAlign="Right" width="90"></e-column>
            <e-column field="Symptoms" headerText="Symptoms" width="140"></e-column>
            <e-column field="Diagnosis" headerText="Diagnosis" width="100"></e-column>
            <e-column field="DoctorDetails" headerText="Doctor Information" width="140"></e-column>
        </e-columns>
      </ejs-grid>
    </div>
    <ng-template #toolbarTemplate>
        <div id='toolbar-template'>
          <ejs-textbox #textbox id='smart_search_input' placeholder='Search here' [width]="200"></ejs-textbox>
          <button id='smart_search_button' style="margin-left: 20px;" class="e-btn e-primary" (click)="smartSearch()">Smart Search</button>
        </div>
      </ng-template>

// react/src/ai-components/grid/semantic-search/semantic-search.tsx
import { GridComponent, ColumnsDirective, ColumnDirective, Inject, Toolbar, Page } from '@syncfusion/ej2-react-grids';
import { MedicalRecords, MedicalRecord } from './datasource';
import './semantic-search.css';
import { TextBoxComponent } from '@syncfusion/ej2-react-inputs';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { Query, Predicate } from '@syncfusion/ej2-data';
import { cosineSimilarity } from "../../../cosine-similarity";
import { embeddingModel } from "../../../sen_transformer/embedding_model";

function SemanticSearch() {
    const getEmbeddingsData = async () => {
        for (let record of MedicalRecords) {
            let data: number[] = (await embeddingModel(
                record.DoctorDetails + ' ' + record.PatientID + ' ' + record.Symptoms + ' ' + record.Diagnosis
            )) as number[];
            productEmbeddings[record.RecordID] = data;
        }
    };

    let gridInstance!: GridComponent;
    let productEmbeddings: { [key: string]: number[] } = {};
    const toolbarTemplate = () => {
        return <div id='toolbar-template'>
            <TextBoxComponent id='smart_search_input' placeholder={'Search here'} width={200} />
            <ButtonComponent id='smart_search_button' isPrimary={true} onClick={smartSearch}>Smart Search</ButtonComponent>
        </div>
    };
    const toolbarOptions = [
        { template: toolbarTemplate }
    ];

    function smartSearch() {
        if (gridInstance) {
            let searchEle: HTMLInputElement = gridInstance.element.querySelector('#smart_search_input')!;
            if (searchEle) {
                let searchValue: string = searchEle.value.trim();
                if (searchValue) {
                    gridInstance.showSpinner();
                    ExecutePrompt(searchValue);
                } else {
                    gridInstance.query = new Query();
                }
            }
        }
    }

    async function ExecutePrompt(searchValue: string) {
        let queryVector: any = await embeddingModel(searchValue);
        const similarityThreshold: number = 0.8;
        const outputData = MedicalRecords.filter((record: any) => {
            const similarity = cosineSimilarity(
                productEmbeddings[record.RecordID],
                queryVector
            );
            if (similarity > similarityThreshold) {
                return record;
            }
        });
        gridInstance.hideSpinner();
        if (outputData.length > 0) {
            gridInstance.query = new Query().where(generatePredicate(outputData));
        } else {
            gridInstance.query = new Query().take(0);
        }
    }

    function generatePredicate(filteredData: MedicalRecord[]) {
        let predicates: Predicate[] = [];
        for (let i: number = 0; i < filteredData.length; i++) {
            predicates.push(new Predicate('Symptoms', 'contains', filteredData[i].Symptoms));
        }
        return Predicate.or(predicates);
    }

    return (
        <div className='control-pane'>
            <div className='control-section'>
                <div className="description-container e-card">
                    <div className='e-card-content'>
                        <p>This example shows how the DataGrid presents medical report data. Using Semantic Search, you can find relevant information without needing to use the exact terms. For instance, searching for "stomach" will still bring up reports about "Abdominal pain." The grid updates search results dynamically using local embeddings. Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/grid/Readme.md">here</a>.</p>
                    </div>
                </div>
                <div id='container'>
                    <GridComponent id='SemanticGrid' ref={grid => gridInstance = grid as GridComponent} toolbar={toolbarOptions} dataSource={MedicalRecords} enableAltRow={true} allowTextWrap={true}
                        created={getEmbeddingsData} >
                        <ColumnsDirective>
                            <ColumnDirective field='RecordID' headerText='Record ID' width='90' textAlign='Right' />
                            <ColumnDirective field='PatientID' headerText='Patient ID' width='90' textAlign='Right' />
                            <ColumnDirective field='Symptoms' headerText='Symptoms' width='140' />
                            <ColumnDirective field='Diagnosis' headerText='Diagnosis' width='100' />
                            <ColumnDirective field='DoctorDetails' headerText='Doctor Information' width='140' />
                        </ColumnsDirective>
                        <Inject services={[Page, Toolbar]} />
                    </GridComponent>
                </div>
            </div>
        </div>
    )
}

export default SemanticSearch;
