// react/src/ai-components/gantt/risk-analysis/risk-analysis.tsx
import { GanttComponent, Toolbar, Edit, Selection, ContextMenu, Filter, Sort, Reorder, DayMarkers, CriticalPath, ColumnsDirective, ColumnDirective, Inject } from '@syncfusion/ej2-react-gantt';
import { tasksCollection } from './datasource';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { getAzureChatAIRequest } from '../../../ai-models';

function RiskAnalysis() {
    let ganttInstance: GanttComponent;
    const taskFields = {
        id: 'TaskID',
        name: 'TaskName',
        startDate: 'StartDate',
        duration: 'Duration',
        progress: 'Progress',
        dependency: 'Predecessor',
        baselineStartDate: "BaselineStartDate",
        baselineEndDate: "BaselineEndDate",
        child: 'subtasks',
        indicators: 'Indicators'
    };
    const toolbarTemplate = () => {
        return <ButtonComponent id='toolbarButton' isPrimary={true}>Analyze Risk</ButtonComponent>
    }

    const toolbarOptions = [{
        template: toolbarTemplate, text: 'Analyze Risk'
    }]

    let summary: any = '';
    (window as any).getSummary = (value: any) => {
        if (summary !== '') {
            let isupdated = false;
            for (let i = 0; i < summary.length; i++) {
                if (parseInt(summary[i]['TaskID']) === value.taskId) {
                    isupdated = true;
                    return summary[i]['Summary'];
                }
            }
            if (!isupdated) {
                return '';
            }
        }
        else {
            return '';
        }
    };

    function toolbarClick(args: any) {
        if (args.item.text === 'Analyze Risk') {
            ganttInstance.showSpinner();
            let input = `1, You analyze the project complete collection in below 'TaskCollection' to identify potential risks and suggest mitigation strategies. 
    2, The collection contains the predessor(Dependency) values with type of SS(start to start), SF(Start to finish), FS(finish to start), FF(finish to finish) and the default type is SS. Dependency values not necessory in each task. 
    3, Analyze the complete project task collection duration and if any task get risk whole project and dependent task gets risk.
            Task Collection Data:` + JSON.stringify(tasksCollection) + `Ensure the output is in JSON object format name of 'TaskDetails' alone with + 'Priority' key-high or low risk and 'Summary' key-details of the risk and mitigation strategy and Summary details given format is (TaskID-summary details), don't give another values and avoid any unwanted content or unwanted JSON tags. No other explanation or content to be returned.
    
            Output format:
            "{
            "TaskDetails":[{
            "Priority":value,
            "TaskID": value,
            "Summary":value
            }]
            }"
    
            Don't give anyother format values.`;
            let aioutput = getAzureChatAIRequest({ messages: [{ role: 'user', content: input }] });
            aioutput.then((result: any) => {
                let cleanedJsonData = result.replace(/^```json\n|```\n?$/g, '');
                summary = JSON.parse(cleanedJsonData).TaskDetails;
                ganttInstance.hideSpinner();
                ganttInstance.refresh();
            });
        }
    }

    const rightLabelTemplate = (data: any) => {
        return (
            <div style={{ marginTop: '-7px' }}>
                {data.ganttProperties && (
                    <div id="rightLabel">
                        {(window as any).getSummary(data.ganttProperties)}
                    </div>
                )}
            </div>
        );
    }

    return (
        <div className='control-pane'>
            <div className='control-section'>
                <div className="description-container e-card">
                    <div className='e-card-content '>
                        <p>Using AI, this sample identifies at-risk tasks by analyzing their duration and dependencies, and highlights them with distinctive colors on their taskbars. Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/gantt/Readme.md">here</a>.</p>
                    </div>
                </div>
                <div id='container'>
                    <GanttComponent
                        id="GanttContainer"
                        ref={(gantt: GanttComponent) => ganttInstance = gantt as GanttComponent}
                        dataSource={tasksCollection}
                        allowSorting={true}
                        allowReordering={true}
                        enableContextMenu={true}
                        toolbar={toolbarOptions}
                        taskFields={taskFields}
                        baselineColor='red'
                        editSettings={{
                            allowAdding: true,
                            allowEditing: true,
                            allowDeleting: true,
                            allowTaskbarEditing: true,
                            showDeleteConfirmDialog: true
                        }}
                        allowFiltering={true}
                        gridLines="Both"
                        highlightWeekends={true}
                        queryTaskbarInfo={(args) => {
                            if (summary !== '') {
                                for (let i = 0; i < summary.length; i++) {
                                    if (parseInt(summary[i]['TaskID']) === args.data.ganttProperties.taskId && summary[i]['Priority'] === 'high') {
                                        args.taskbarBgColor = 'rgb(255, 0, 0)';
                                        args.progressBarBgColor = 'rgb(255, 0, 0)';
                                    }
                                }
                            }
                        }}
                        timelineSettings={{
                            showTooltip: true,
                            topTier: {
                                unit: 'Week',
                                format: 'dd/MM/yyyy'
                            },
                            bottomTier: {
                                unit: 'Day',
                                count: 1
                            }
                        }}
                        labelSettings={{
                            rightLabel: rightLabelTemplate,
                            taskLabel: '${Progress}%'
                        }}
                        toolbarClick={toolbarClick}
                        readOnly={false}
                        taskbarHeight={20}
                        rowHeight={40}
                        height='550px'
                        treeColumnIndex={1}
                        allowUnscheduledTasks={true}
                        projectStartDate={new Date('03/25/2019')}
                        projectEndDate={new Date('05/30/2019')}
                    >
                        <ColumnsDirective>
                            <ColumnDirective field='TaskID' headerText='Task ID' visible={false} />
                            <ColumnDirective field='TaskName' headerText='Event Name' allowReordering={false} width='250px' />
                            <ColumnDirective field='Duration' headerText='Duration' allowEditing={false} />
                            <ColumnDirective field='StartDate' headerText='Start Date' allowSorting={false} />
                            <ColumnDirective field='EndDate' headerText='End Date' allowSorting={false} />
                        </ColumnsDirective>
                        <Inject services={[Edit, Toolbar, Selection, CriticalPath, ContextMenu, Filter, Sort, Reorder, DayMarkers]} />
                    </GanttComponent>
                </div>
            </div>
        </div>
    )
}

export default RiskAnalysis

// angular/src/app/gantt/risk-analysis/risk-analysis.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { tasksCollection } from './ganttdata';
import { getAzureChatAIRequest } from '../../ai-models/ai-models';
import { ToolbarModule } from '@syncfusion/ej2-angular-navigations'
import { ToolbarService } from '@syncfusion/ej2-angular-gantt'
import { GanttAllModule } from '@syncfusion/ej2-angular-gantt';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-risk-analysis',
  standalone: true,
  imports: [GanttAllModule, ToolbarModule, CommonModule],
  providers: [ToolbarService],
  templateUrl: './risk-analysis.component.html',
  styleUrl: './risk-analysis.component.css'
})
export class RiskAnalysisComponent {
  @ViewChild('ganttDefault', { static: false }) gantt!: ElementRef;
  public bool=true;
  public data?: object[];
  public taskSettings?: object;
  public editSetting?: object;
  public splitterSettings?: object;
  public toolbar?: object[];
  public baselineColor: string = 'red';
  public projectStartDate = new Date('03/25/2019');
  public projectEndDate =  new Date('05/30/2019');
  public gridLines: string = "Both";
  public summary: any = '';
  public timelineSettings?: object;
  public labelSettings?: object;
  ngOnit() {
    this.data = tasksCollection;
    this.taskSettings = {
      id: 'TaskID',
      name: 'TaskName',
      startDate: 'StartDate',
      duration: 'Duration',
      progress: 'Progress',
      dependency: 'Predecessor',
      baselineStartDate: "BaselineStartDate",
      baselineEndDate: "BaselineEndDate",
      child: 'subtasks',
      indicators: 'Indicators'
    };
    this.editSetting = {
      allowAdding: true,
      allowEditing: true,
      allowDeleting: true,
      allowTaskbarEditing: true,
      showDeleteConfirmDialog: true
    };
    this.splitterSettings = {
      position: "28%"
    };
    this.labelSettings = {
      rightLabel: this.getSummary.bind(this),
      taskLabel: '${Progress}%'
    };
    this.toolbar = [{template: '<button id="toolbarButton" class="e-btn e-primary">Predict milestone</button>', text:'Predict milestone' }];
    this.timelineSettings = {
      showTooltip: true,
      topTier: {
        unit: 'Week',
        format: 'dd/MM/yyyy'
      },
      bottomTier: {
        unit: 'Day',
        count: 1
      }
    }

  }

  public getSummary(value: any): any {
         if (this.summary !== '') {
           let isupdated = false;
           for (let i = 0; i < this.summary.length; i++) {
             if (parseInt(this.summary[i]['TaskID']) === value.taskId) {
               isupdated = true;
               return this.summary[i]['Summary'];
             }
           }
           if (!isupdated) {
             return '';
           }
         }
         else {
           return '';
         }
       };
  public queryTaskbarInfo(args: any) {
    debugger
    if (this.summary !== '') {
      for (let i = 0; i < this.summary.length; i++) {
        if (parseInt(this.summary[i]['TaskID']) === args.data.ganttProperties.taskId && this.summary[i]['Priority'] === 'high') {
          args.taskbarBgColor = 'rgb(255, 0, 0)';
          args.progressBarBgColor = 'rgb(255, 0, 0)';
        }
      }
    }
  }




  public toolbarClick(args: any) {
    if (args.item.text === 'Analyze Risk') {
     console.log( (this.gantt as any).ganttProperties);
      (this.gantt as any).showSpinner();

      let input = `1, You analyze the project complete collection in below 'TaskCollection' to identify potential risks and suggest mitigation strategies. 
2, The collection contains the predessor(Dependency) values with type of SS(start to start), SF(Start to finish), FS(finish to start), FF(finish to finish) and the default type is SS. Dependency values not necessory in each task. 
3, Analyze the complete project task collection duration and if any task get risk whole project and dependent task gets risk.
        Task Collection Data:` + JSON.stringify(tasksCollection) + `Ensure the output is in JSON object format name of 'TaskDetails' alone with + 'Priority' key-high or low risk and 'Summary' key-details of the risk and mitigation strategy and Summary details given format is (TaskID-summary details), don't give another values and avoid any unwanted content or unwanted JSON tags. No other explanation or content to be returned.

        Output format:
        "{
        "TaskDetails":[{
        "Priority":value,
        "TaskID": value,
        "Summary":value
        }]
        }"

        Don't give anyother format values.`;
      let aioutput = getAzureChatAIRequest({ messages: [{ role: 'user', content: input }] });
      aioutput.then((result: any) => {
        let cleanedJsonData = result.replace(/^```json\n|```\n?$/g, '');
        this.summary = JSON.parse(cleanedJsonData).TaskDetails;
        (this.gantt as any).hideSpinner();
        (this.gantt as any).refresh();
        // setTimeout(() => {
        //     button.refresh()
            
        // }, 500);
      });
    }
  }
}

<h2 style="text-align: center;">Smart Risk Assessor</h2>
<div class="description-container e-card">
  <div class='e-card-content'>
    <p>
      This sample highlights at-risk tasks in the Angular Gantt Chart based on their duration and dependencies by dynamically changing their taskbar colors, making it easy to visualize potential project risks.
    </p>
  </div>
</div>

<div id='container'>
  <ejs-gantt 
    #ganttDefault 
    height="430px" 
    [dataSource]="data" 
    [taskFields]="taskSettings"  
    [editSettings]="editSetting"
    [allowSorting]="true" 
    [allowReordering]="true" 
    [allowSelection]="true" 
    [treeColumnIndex]="1" 
    [enableContextMenu]="true"
    [baselineColor]="baselineColor" 
    [allowFiltering]="true" 
    [gridLines]="gridLines" 
    [highlightWeekends]="true"
    [timelineSettings]="timelineSettings" 
    [labelSettings]="labelSettings"
    [readOnly]="false" 
    [taskbarHeight]="20" 
    [rowHeight]="40"
    [allowUnscheduledTasks]="true" 
    (queryTaskbarInfo)="queryTaskbarInfo($event)"
    [splitterSettings]="splitterSettings" 
    [toolbar]="toolbar" 
    (toolbarClick)="toolbarClick($event)" 
    [projectStartDate]="projectStartDate" 
    [projectEndDate]="projectEndDate">

    <e-columns>
      <e-column field='TaskID' headerText='Task ID' [visible]="false"></e-column>
      <e-column field='TaskName' headerText='Event Name' [width]="250"></e-column>
      <e-column field='Duration'></e-column>
      <e-column field='StartDate' headerText='Start Date'></e-column>
      <e-column field='EndDate' headerText='End Date'></e-column>
    </e-columns> 
    
    <!-- Directly render the rightLabel template -->
    <ng-template #rightLabel let-data>
      <div id="rightLabel">
        {{ getSummary(data) }}
      </div>
    </ng-template>
    
  </ejs-gantt>

  <div id="csfooter" style="width: 100%; height: 66px; background-color: #F0FFFF; min-height: 120px; padding: 15px;"></div>
</div>
