// vue/src/App.vue
<template>
    <ejs-appbar id="e-header">
        <ejs-button id='regularButtonMenu' cssClass="e-inherit menu" iconCss="e-icons e-menu"
            @click="hamburgerClick"></ejs-button>
        <span class="regular">Syncfusion Vue AI Samples</span>
        <div class="e-appbar-spacer"></div>
    </ejs-appbar>
    <div id="control-panel">
        <div id="right-pane">
            <router-view />
        </div>
    </div>
    <ejs-sidebar ref="leftpane" id="left-pane" class="default-sidebar" width="260px" target="#control-panel" type="Auto"
        position="Left">
        <ejs-treeview id='flat-list' nodeTemplate="nodeTemplate" :fields='fields' :dataSource='dataSource'>
            <template #nodeTemplate="{ data }">
                <router-link v-if="data.path" :to="data.path">{{ data.name }}</router-link>
                <span v-else>{{ data.name }}</span>
            </template>
        </ejs-treeview>
    </ejs-sidebar>
</template>

<script>
import { SidebarComponent, AppBarComponent } from '@syncfusion/ej2-vue-navigations';
import { TreeViewComponent } from '@syncfusion/ej2-vue-navigations';
import { ButtonComponent } from '@syncfusion/ej2-vue-buttons';
import data from './sample.json'
import { enableRipple } from '@syncfusion/ej2-base';

enableRipple(true);

export default {
    name: "App",
    components: {
        "ejs-sidebar": SidebarComponent,
        "ejs-treeview": TreeViewComponent,
        'ejs-appbar': AppBarComponent,
        'ejs-button': ButtonComponent
    },
    data() {
        return {
            fields: { dataSource: data, text: 'name', id: 'id', child: 'children', navigateURL: "path" },
            dataSource: data
        };
    },
    methods: {
        hamburgerClick: function () {
            this.$refs.leftpane.toggle();
        },
        
    }
}
</script>

// react/src/App.tsx
import { Outlet } from "react-router-dom";
import { ItemDirective, ItemsDirective, SidebarComponent, ToolbarComponent } from '@syncfusion/ej2-react-navigations';
import LeftPane from './left-pane';
import './App.css'

function App() {
  let sidebarObj: SidebarComponent;
  const target: string = '.main-content';
  const title: string = '<div class="sample-name"><strong>Syncfusion React AI Samples</strong></div>';

  function toolbarClicked(args: any) {
    if (args.item.tooltipText == "Controls") {
      sidebarObj.toggle();
    }
  }

  return (
    <>
      <div id="container">
        <div>
          <ToolbarComponent id="menuToolbar" clicked={toolbarClicked}>
            <ItemsDirective>
              <ItemDirective id="menu-toggle" prefixIcon="e-icons e-menu" tooltipText="Controls"></ItemDirective>
              <ItemDirective template={title}></ItemDirective>
            </ItemsDirective>
          </ToolbarComponent>
        </div>
        <div className='main-content'>
          <SidebarComponent id="home-sidebar" ref={Sidebar => (sidebarObj as any) = Sidebar} width={'270px'}
            target={target} isOpen={true} type='Auto'>
            <LeftPane />
          </SidebarComponent>
          <div className='right-pane'>
            <div className='header-text'></div>
            <div id="content">
              {/* Routing content declaration */}
              <Outlet />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default App
