// react/src/ai-components/gantt/prioritize-task/prioritize-task.tsx
import { GanttComponent, Toolbar, Edit, Selection, ColumnsDirective, ColumnDirective, Inject } from '@syncfusion/ej2-react-gantt';
import { tasksCollection, resourceCollection } from './datasource';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { getAzureChatAIRequest } from '../../../ai-models';
import './prioritize-task.css';

function PrioritizeTask() {
    let ganttInstance: GanttComponent;
    const taskFields = {
        id: 'Id',
        name: 'Name',
        startDate: 'StartDate',
        endDate: 'EndDate',
        progress: 'Progress',
        parentID: 'ParentId',
        resourceInfo: 'resourceInfo',
        baselineStartDate: "BaselineStartDate",
        baselineEndDate: "BaselineEndDate",
    };
    const toolbarTemplate = () => {
        return <ButtonComponent id='toolbarButton' isPrimary={true}>Assign prioritize tasks</ButtonComponent>
    }

    const toolbarOptions = [{
        template: toolbarTemplate, text: 'Assign prioritize tasks'
    }]

    function toolbarClick(args: any) {
        if (args.item.text === 'Assign prioritize tasks') {
            ganttInstance.showSpinner();
            let input = `
          Analyze the following TaskCollection to identify critical tasks. 
          A task is considered critical if its EndDate is greater than its BaselineEndDate, comparing only the dates (not the time). 
          Both EndDate and BaselineEndDate must not be null.
          Here is the 'TaskCollection': ${JSON.stringify(tasksCollection)};
          For each task, add an additional property called isCritical. Set this property to true if the task is critical based on the criteria provided, otherwise set it to false. 
          Ensure that:
          1. Only the date part (not time) of EndDate and BaselineEndDate is compared.
          2. Tasks with both EndDate and BaselineEndDate being not null and where EndDate is greater than BaselineEndDate are marked as critical.
          Return the entire modified TaskCollection in JSON format. Ensure all tasks are included with their updated isCritical property. Do not include any other text or additional information.`
            let prompt = input;
            let aioutput = getAzureChatAIRequest({ messages: [{ role: 'user', content: prompt }] });
            aioutput.then((result: any) => {
                let cleanedJsonData = result.replace(/^```json\n|```\n?$/g, '');
                cleanedJsonData = cleanedJsonData.replace(/\n}\n/g, '');
                let input1 = `Analyze the following JSON data:
    
            - 'TaskCollection': ${JSON.stringify(tasksCollection)}
            - 'ResourceCollection': ${JSON.stringify(resourceCollection)}
            - 'CriticalCollection': ${JSON.stringify(cleanedJsonData)}
            
            Perform the following steps:
            1. For each task in 'CriticalCollection' where 'isCritical' is 'true':
               - Identify unassigned resources by comparing 'ResourceCollection' with the 'resourceInfo' property in 'TaskCollection'.
               - Add each unassigned resource to the 'resourceInfo' property of the corresponding critical task without removing any existing resources.
               - Ensure that each critical task receives a unique unassigned resource, if available.
            
            Return the modified 'CriticalCollection' with the additional resources assigned.
            
            Additionally, create a new property called 'AddedResourceIds' that contains the IDs of tasks in 'CriticalCollection' where 'isCritical' is 'true' and additional resources were added.
            
            Provide the result in JSON format, including:
            - The modified 'CriticalCollection'.
            - The 'AddedResourceIds' property with the IDs of tasks where additional resources were added.
            
            Do not include any additional text or information.`
                let aioutput1 = getAzureChatAIRequest({ messages: [{ role: 'user', content: input1 }] });
                aioutput1.then((result: any) => {
                    let cleanedJsonData1 = result.replace(/^```json\n|```\n?$/g, '');
                    let criticalTask = JSON.parse(cleanedJsonData1);
                    ganttInstance.dataSource = criticalTask.CriticalCollection
                    let modifiedtaskID = criticalTask.AddedResourceIds;
                    let taskIdsString = modifiedtaskID.join(', ');
                    let csfooterElement = document.getElementById('csfooter');
                    if (csfooterElement) {
                        csfooterElement.innerText = ' Critical task containing Task Id: ' + taskIdsString + ' new resources has been added';
                    }
                    ganttInstance.hideSpinner();
                })
            });
        }
    }

    return (
        <div className='control-pane'>
            <div className='control-section'>
                <div className="description-container e-card">
                    <div className='e-card-content '>
                        <p>This sample uses AI to identify critical tasks based on the project schedule. The AI then prompts for resource reassignment and generates a summary outlining the reallocation process and details of the critical tasks. Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/gantt/Readme.md">here</a>.</p>
                    </div>
                </div>
                <div id='container'>
                    <GanttComponent
                        ref={(gantt: GanttComponent) => ganttInstance = gantt as GanttComponent}
                        dataSource={tasksCollection}
                        resources={resourceCollection}
                        taskFields={taskFields}
                        resourceFields={{
                            id: 'Id',
                            name: 'Name',
                            unit: 'MaxUnit',
                        }}
                        editSettings={{
                            allowAdding: true,
                            allowEditing: true,
                            allowDeleting: true,
                            allowTaskbarEditing: true,
                            showDeleteConfirmDialog: true
                        }}
                        rowDataBound={(args) => {
                            if (args.data.taskData.isCritical) {
                                args.row.style.backgroundColor = '#ffecd4';
                            }
                        }}
                        queryTaskbarInfo={(args) => {
                            if (args.data.taskData.isCritical) {
                                args.taskbarElement.parentElement.parentElement.style.backgroundColor = '#ffecd4';
                            }
                        }}
                        columns={[
                            { field: 'Id', headerText: "Task Id", visible: false },
                            { field: 'Name', headerText: 'Task Name', width: 250, clipMode: 'EllipsisWithTooltip' },
                            { field: 'resourceInfo', headerText: 'Resources' },
                            { field: 'StartDate', headerText: 'Start Date' },
                            { field: 'EndDate', headerText: 'End Date' },
                        ]}
                        toolbar={toolbarOptions}
                        toolbarClick={toolbarClick}
                        labelSettings={{
                            rightLabel: 'resourceInfo'
                        }}
                        splitterSettings={{
                            position: "23%"
                        }}
                        readOnly={false}
                        allowSelection={true}
                        highlightWeekends={true}
                        treeColumnIndex={1}
                        taskbarHeight={20}
                        rowHeight={40}
                        height='550px'
                    >
                        <ColumnsDirective>
                            <ColumnDirective field='Id' headerText='Task Id' visible={false} />
                            <ColumnDirective field='Name' headerText='Task Name' width={250} clipMode='EllipsisWithTooltip' />
                            <ColumnDirective field='resourceInfo' headerText='Resources' />
                            <ColumnDirective field='StartDate' headerText='Start Date' />
                            <ColumnDirective field='EndDate' headerText='End Date' />
                        </ColumnsDirective>
                        <Inject services={[Edit, Toolbar, Selection]} />
                    </GanttComponent>
                    <div id="csfooter"></div>
                </div>
            </div>
        </div>
    )
}

export default PrioritizeTask

// angular/src/app/gantt/prioritize-task/prioritize-task.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { GanttModule } from '@syncfusion/ej2-angular-gantt';
import { tasksCollection, resourceCollection } from './ganttdata';
import { ToolbarModule } from '@syncfusion/ej2-angular-navigations'
import { ToolbarService } from '@syncfusion/ej2-angular-gantt'
import {getAzureChatAIRequest } from '../../ai-models/ai-models';


@Component({
  selector: 'app-prioritize-task',
  standalone: true,
  imports: [
    GanttModule,ToolbarModule
  ],
  providers: [ToolbarService],
  templateUrl: './prioritize-task.component.html',
  styleUrl: './prioritize-task.component.css'
})
export class PrioritizeTaskComponent {
  @ViewChild('ganttDefault', { static: false }) gantt!: ElementRef;
  public data?: object[];
  public resource?: object[];
  public taskSettings?: object;
  public resourceSettings?: object;
  public labelSettings?:object;
  public splitterSettings?:object;
  public editSetting?:object;
  public mode:string= "EllipsisWithTooltip";
  public toolbar?:object[];
  
  public ngOnInit(): void {
    this.data = tasksCollection;
    this.resource = resourceCollection;
    this.taskSettings = {
      id: 'Id',
      name: 'Name',
      startDate: 'StartDate',
      endDate: 'EndDate',
      progress: 'Progress',
      parentID: 'ParentId',
      resourceInfo: 'resourceInfo',
      baselineStartDate: "BaselineStartDate",
      baselineEndDate: "BaselineEndDate",
    };
    this.resourceSettings = {
      id: 'Id',
      name: 'Name',
      unit: 'MaxUnit',
    };
    this.labelSettings= {
      rightLabel: 'resourceInfo'
  }
  this.splitterSettings= {
    position: "23%"
}
    this.editSetting = {
      allowAdding: true,
      allowEditing: true,
      allowDeleting: true,
      allowTaskbarEditing: true,
      showDeleteConfirmDialog: true
  }
  this.toolbar=[{template: '<button id="toolbarButton" class="e-btn e-primary">Assign prioritize tasks</button>', text:'Assign prioritize tasks' }]
}

public rowDataBound(args:any){
  if (args.data.taskData.isCritical) {
      args.row.style.backgroundColor = '#ffecd4';
  }
}
public queryTaskbarInfo(args:any) {
  if (args.data.taskData.isCritical) {
      args.taskbarElement.parentElement.parentElement.style.backgroundColor = '#ffecd4';
  }
}

public toolbarClick(args: any) {
  debugger
  if (args.item.text === 'Assign prioritize tasks') {
    (this.gantt as any).showSpinner();
      let input = `
    Analyze the following TaskCollection to identify critical tasks. 
    A task is considered critical if its EndDate is greater than its BaselineEndDate, comparing only the dates (not the time). 
    Both EndDate and BaselineEndDate must not be null.
    Here is the 'TaskCollection': ${JSON.stringify(tasksCollection)};
    For each task, add an additional property called isCritical. Set this property to true if the task is critical based on the criteria provided, otherwise set it to false. 
    Ensure that:
    1. Only the date part (not time) of EndDate and BaselineEndDate is compared.
    2. Tasks with both EndDate and BaselineEndDate being not null and where EndDate is greater than BaselineEndDate are marked as critical.
    Return the entire modified TaskCollection in JSON format. Ensure all tasks are included with their updated isCritical property. Do not include any other text or additional information.`
    let prompt = input;
    debugger
    let aioutput = getAzureChatAIRequest({ messages: [{ role: 'user', content: prompt }] });
    aioutput.then((result: any) => {
      let cleanedJsonData = result.replace(/^```json\n|```\n?$/g, '');
      cleanedJsonData = cleanedJsonData.replace(/\n}\n/g, '');
      let criticalTask = JSON.parse(cleanedJsonData);
      let input1 = `Analyze the following JSON data:

      - 'TaskCollection': ${JSON.stringify(tasksCollection)}
      - 'ResourceCollection': ${JSON.stringify(resourceCollection)}
      - 'CriticalCollection': ${JSON.stringify(cleanedJsonData)}
      
      Perform the following steps:
      1. For each task in 'CriticalCollection' where 'isCritical' is 'true':
         - Identify unassigned resources by comparing 'ResourceCollection' with the 'resourceInfo' property in 'TaskCollection'.
         - Add each unassigned resource to the 'resourceInfo' property of the corresponding critical task without removing any existing resources.
         - Ensure that each critical task receives a unique unassigned resource, if available.
      
      Return the modified 'CriticalCollection' with the additional resources assigned.
      
      Additionally, create a new property called 'AddedResourceIds' that contains the IDs of tasks in 'CriticalCollection' where 'isCritical' is 'true' and additional resources were added.
      
      Provide the result in JSON format, including:
      - The modified 'CriticalCollection'.
      - The 'AddedResourceIds' property with the IDs of tasks where additional resources were added.
      
      Do not include any additional text or information. Also strictly return the JSON data in the format mentioned above.`
        let aioutput1 = getAzureChatAIRequest({ messages: [{ role: 'user', content: input1 }] });
        aioutput1.then((result: any) => {
            let cleanedJsonData1 = result.replace(/^```json\n|```\n?$/g, '');
            let criticalTask1 = JSON.parse(cleanedJsonData1);
            (this.gantt as any).dataSource = criticalTask1.CriticalCollection
            let modifiedtaskID = criticalTask1.AddedResourceIds;
            let taskIdsString = modifiedtaskID.join(', ');
            let csfooterElement = document.getElementById('csfooter');
            if (csfooterElement) {
                csfooterElement.innerText = ' Critical task containing Task Id: ' + taskIdsString + ' new resources has been added';
            }
            (this.gantt as any).hideSpinner();
        })
    });
  }
}

}


<h2 style="text-align: center;">Smart Prioritizer</h2>
<div class="description-container e-card">
    <div class='e-card-content '>
        <!--!-->
        <p>
            This sample shows how AI prioritizes tasks within a collection by evaluating baseline dates and scheduled taskbar dates. The AI identifies critical tasks essential for meeting project deadlines and reallocates resources to these tasks, ensuring efficient management and timely project completion.   
        </p>
    </div>
</div>

<div id='container'>
        <ejs-gantt #ganttDefault height="430px" [dataSource]="data" [taskFields]="taskSettings" [resourceFields]="resourceSettings" [resources]="resource"
        [editSettings]="editSetting" [readOnly]="false" [allowSelection]="true" [highlightWeekends]="true" [treeColumnIndex]="1"  [rowHeight]="40"
        [labelSettings]="labelSettings" [splitterSettings]="splitterSettings" [toolbar]="toolbar" (toolbarClick)="toolbarClick($event)" (rowDataBound)="rowDataBound($event)" (queryTaskbarInfo)="queryTaskbarInfo($event)">
        <e-columns>
            <e-column field='ID' headerText='Task ID' [visible]="false"></e-column>
            <e-column field='Name' headerText='Task Name' [clipMode]="mode"></e-column>
            <e-column field='resourceInfo' headerText='Resources'></e-column>
            <e-column field='StartDate' headerText='Start Date' ></e-column>
            <e-column field='EndDate' headerText='End Date'></e-column>
        </e-columns> 
        </ejs-gantt>
    <!-- <div id="csfooter" style="width: 100%; height: 66px; background-color: #F0FFFF;min-height: 120px; padding: 15px;"></div> -->
</div>
