// react/src/ai-components/document-editor/smart-editor/smart-editor.tsx
import { DocumentEditorContainerComponent, Toolbar, Inject, CustomContentMenuEventArgs, BeforeOpenCloseCustomContentMenuEventArgs } from "@syncfusion/ej2-react-documenteditor"
import { useEffect, useRef } from "react";
import { TitleBar } from "../title-bar";
import { sfdtData } from "./datasource";
import { ItemDirective, MenuItemModel, ToolbarComponent } from "@syncfusion/ej2-react-navigations";
import './smart-editor.css';
import { createSpinner, DialogComponent, hideSpinner, OpenEventArgs, showSpinner } from "@syncfusion/ej2-react-popups";
import { ItemsDirective, SplitterComponent } from "@syncfusion/ej2-react-layouts";
import { ChangeEventArgs, CheckBoxSelection, ComboBoxComponent, MultiSelectChangeEventArgs, MultiSelectComponent } from "@syncfusion/ej2-react-dropdowns";
import { getAzureChatAIRequest } from "../../../azure-openai";

interface Message {
    role: string;
    content: string;
}

interface AzureAIRequestOptions {
    messages: Message[];
    model: string;
}

function SmartEditor() {
    let container = useRef<DocumentEditorContainerComponent>(null);
    let titleBar: TitleBar;
    let dialog: DialogComponent;
    let toolbar: ToolbarComponent;
    let questionDiv: HTMLDivElement;
    let editableDiv: HTMLDivElement;

    //toolbar

    let toneValue: string = 'Professional';
    let formatValue: string = 'Paragraph';
    let lengthValue: string = 'Medium';
    let outList: string[] = [];
    let translateValue: string = 'French';
    let grammerList: string[] = [];

    let toneList: string[] = ['Professional', 'Friendly', 'Instructional', 'Marketing', 'Academic', 'Legal', 'Technical', 'Narrative', 'Direct'];
    let formatValueList: string[] = ['Paragraph', 'Blog post', 'Technical Documentation', 'Report', 'Research Papers', 'Tutorial', 'Meeting Notes'];
    let lengthList: string[] = ['Short', 'Medium', 'Long'];

    let languageList: string[] = ['Simplified Chinese', 'Spanish', 'French', 'Arabic', 'Portuguese', 'Russian', 'Urdu', 'Indonesian', 'German', 'Japanese'];
    let grammer: { [key: string]: Object }[] = [
        { id: 'SVA', name: 'Subject-Verb Agreement' },
        { id: 'TC', name: 'Tense Consistency' },
        { id: 'PA', name: 'Pronoun Agreement' },
        { id: 'CU', name: 'Comma Usage' },
        { id: 'PS', name: 'Parallel Structure' },
        { id: 'MM', name: 'Misplaced Modifiers' },
        { id: 'DM', name: 'Dangling Modifiers' },
        { id: 'WC', name: 'Word Choice' },
        { id: 'R', name: 'Redundancy' },
        { id: 'UA', name: 'Use of Articles' },
        { id: 'PM', name: 'Punctuation Marks' },
        { id: 'APC', name: 'Apostrophes for Possessives and Contractions' },
        { id: 'SE', name: 'Spelling Errors' }
    ];

    let menuItems: MenuItemModel[] = [
        {
            text: 'Rewrite',
            id: 'rewrite',
            iconCss: 'e-icons e-edit'
        },
        {
            text: 'Translate',
            id: 'translate',
            iconCss: 'e-icons e-transform-right'
        },
        {
            text: 'Grammar',
            id: 'grammer',
            iconCss: 'e-icons e-redaction'
        },
    ];
    useEffect(() => {
        window.onbeforeunload = function () {
            return "Want to save your changes?";
        };
        container.current!.documentEditor.pageOutline = "#E0E0E0";
        container.current!.documentEditor.acceptTab = true;
        container.current!.documentEditor.resize();
        if (!titleBar) {
            titleBar = new TitleBar(
                document.getElementById("documenteditor_titlebar")!,
                container.current!.documentEditor,
                true
            );
        }
        onLoadDefault();
    }, []);


    const onLoadDefault = (): void => {
        // tslint:disable
        let defaultDocument: object = {
            sfdt: sfdtData
        };
        // tslint:enable
        container.current!.documentEditor.open(JSON.stringify(defaultDocument));
        container.current!.documentEditor.documentName = "Getting Started";
        titleBar.updateDocumentTitle();
        container.current!.documentEditor.contextMenu.addCustomMenu(menuItems, false);

        container.current!.documentEditor.customContextMenuBeforeOpen = (args: BeforeOpenCloseCustomContentMenuEventArgs): void => {
            let isEmpty: boolean = container.current!.documentEditor.selection.isEmpty;
            for (let i: number = 0; i < args.ids.length; i++) {
                let element: HTMLElement = document.getElementById(args.ids[i])!;
                if (!isEmpty) {
                    element.style.display = 'block';
                } else {
                    element.style.display = 'none';
                }
            }
        };

        container.current!.customContextMenuSelect = (args: CustomContentMenuEventArgs): void => {
            let item: string = args.id;
            let id: string = container.current!.element.id;
            switch (item) {
                case id + '_editorrewrite':
                    onRewrite();
                    break;
                case id + '_editortranslate':
                    onTranslate();
                    break;
                case id + '_editorgrammer':
                    onGrammerCheck();
                    break;
            }
        };
    };

    function onRewrite() {
        dialog.header = 'AI Rephrase';
        dialog.show();
        questionDiv!.innerText = container.current!.documentEditor.selection.text;
        onChangeToolbarVisibility(true, false, false);
        onRewriteClick();
    }

    function onTranslate() {
        dialog.header = 'AI Translate';
        dialog.show();
        questionDiv!.innerText = container.current!.documentEditor.selection.text;
        onChangeToolbarVisibility(false, true, false);
        onTranslateClick();
    }

    function onGrammerCheck() {
        dialog.header = 'Grammer';
        dialog.show();
        questionDiv!.innerText = container.current!.documentEditor.selection.text;
        onChangeToolbarVisibility(false, false, true);
        onGrammerCheckClick();
    }

    function onBeforeOpen(): void {
        onChangeToolbarVisibility(true, false, false);
    }
    function onclose(): void {
        clearContent();
    }
    function onOpen(args: OpenEventArgs): void {
        args.preventFocus = true;
    }

    async function onToolbarCreated() {
        updateIndex();
    }
    // multiSelect.selectAll(true);
    function onSettingsClick() {
        onChangeToolbarVisibility(false, false, false);
    }

    function onCloseSecndaryToolbar() {
        onChangeToolbarVisibility(true, false, false);
    }

    function onToneChange(args: ChangeEventArgs): void {
        toneValue = args.value as string;
    }
    function onFormatChange(args: ChangeEventArgs): void {
        formatValue = args.value as string;
    }
    function onLengthChange(args: ChangeEventArgs): void {
        lengthValue = args.value as string;
    }
    function onLanguageChange(args: ChangeEventArgs): void {
        translateValue = args.value as string;
    }

    function ValueChangeHandler(args: MultiSelectChangeEventArgs): void {
        grammerList = args.value as string[];
    }

    function onChangeToolbarVisibility(showPryItem: boolean, showTranslateItem: boolean, showGrammerItem: boolean) {
        let isPrimary: boolean = false;
        let isSecondary: boolean = true;
        let isTranslate: boolean = false;
        let isGrammer: boolean = false;
        if (showPryItem) {
            isPrimary = true;
            isSecondary = false;
            isTranslate = false;
            isGrammer = false;
        }
        if (showTranslateItem) {
            isPrimary = false;
            isSecondary = false;
            isTranslate = true;
            isGrammer = false;
        }
        if (showGrammerItem) {
            isPrimary = false;
            isSecondary = false;
            isTranslate = false;
            isGrammer = true;
        }
        for (let i = 0; i < 5; i++) {
            toolbar.items[i].visible = isPrimary;
            toolbar.items[i + 5].visible = isSecondary;
        }
        toolbar.items[10].visible = isTranslate;
        toolbar.items[11].visible = isTranslate;
        toolbar.items[12].visible = isGrammer;
        toolbar.items[13].visible = isGrammer;
    }

    // spinner
    createSpinner({
        target: document.getElementById('dialog') as HTMLElement,
    });

    async function onRewriteClick() {
        showSpinner(document.getElementById('dialog') as HTMLElement);
        let text: string = questionDiv!.innerText;
        const options: AzureAIRequestOptions = {
            messages: [
                { role: "system", content: `You are a helpful assistant. Your task is to analyze the provided text and rephrase it. Please adjust the text to reflect a tone of '${toneValue}', formatted in '${formatValue}' style, and maintain a length of '${lengthValue}'. Always respond in proper HTML format, excluding <html>, <head>, and <body> tags.` },
                { role: "user", content: text }
            ],
            model: "gpt-4",
        };
        await onGenerate(options);
        hideSpinner(document.getElementById('dialog') as HTMLElement);
    }

    async function onTranslateClick() {
        showSpinner(document.getElementById('dialog') as HTMLElement);
        let text: string = questionDiv!.innerText;
        const options: AzureAIRequestOptions = {
            messages: [
                { role: "system", content: `You are a helpful assistant. Your task is to translate the provided text into '${translateValue}'. Always respond in proper HTML format, excluding <html> and <head> tags.` },
                { role: "user", content: text }
            ],
            model: "gpt-4",
        };
        await reframeContent(options);
        hideSpinner(document.getElementById('dialog') as HTMLElement);
    }

    async function onGrammerCheckClick() {
        showSpinner(document.getElementById('dialog') as HTMLElement);
        let value: string = '';
        let systemPrompt: string = '';
        if (grammerList.length > 0) {
            grammerList.forEach((item) => {
                value += item + ', ';
            });
            systemPrompt = `You are a helpful assistant. Your task is to analyze the provided text and perform the following grammar checks: ${value}. Please ensure that the revised text reflects these corrections. Always respond in proper HTML format, but do not include <html>, <head>, or <body> tags.`;
        } else {
            systemPrompt = "You are a helpful assistant. Your task is to analyze the provided text, check for and correct any grammatical errors, and rephrase it. Always respond in proper HTML format, but do not include <html>, <head>, or <body> tags.";
        }
        let text: string = questionDiv!.innerText;
        const options: AzureAIRequestOptions = {
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: text }
            ],
            model: "gpt-4",
        };
        await reframeContent(options);
        hideSpinner(document.getElementById('dialog') as HTMLElement);
    }

    async function onGenerate(options: AzureAIRequestOptions): Promise<void> {
        outList = [];
        for (let i = 0; i < 3; i++) {
            const response = await getAzureChatAIRequest(options);
            if (response && outList.indexOf(response) === -1) {
                outList.push(response);
            } else {
                i--;
            }
        }
        if (outList.length > 0) {
            editableDiv!.innerHTML = outList[0];
            updateIndex();
        }
    }

    async function reframeContent(options: AzureAIRequestOptions): Promise<void> {
        const response = await getAzureChatAIRequest(options);
        if (response) {
            editableDiv!.innerHTML = response;
        }
    }

    function moveToNext() {
        let text: string = editableDiv!.innerHTML;
        let index: number = outList.indexOf(text);
        if (index + 1 < outList.length) {
            editableDiv!.innerHTML = outList[index + 1];
            updateIndex();
        }
    }

    function moveToPrevious() {
        let text: string = editableDiv!.innerHTML;
        let index: number = outList.indexOf(text);
        if (index - 1 >= 0) {
            editableDiv!.innerHTML = outList[index - 1];
            updateIndex();
        }
    }

    function moveToNextPara() {
        editableDiv!.innerHTML = '';
        container.current!.documentEditor.selection.moveToParagraphEnd();
        container.current!.documentEditor.selection.moveToNextLine();
        container.current!.documentEditor.selection.selectParagraph();
        questionDiv!.innerText = container.current!.documentEditor.selection.text;
        if (dialog.header === 'AI Translate') {
            onTranslateClick();
        } else if (dialog.header === 'AI Rephrase') {
            onRewriteClick();
        } else {
            onGrammerCheckClick();
        }
    }

    function moveToPreviousPara() {
        editableDiv!.innerHTML = '';
        container.current!.documentEditor.selection.moveToParagraphEnd();
        container.current!.documentEditor.selection.moveToNextLine();
        container.current!.documentEditor.selection.selectParagraph();
        questionDiv!.innerText = container.current!.documentEditor.selection.text;
        if (dialog.header === 'AI Translate') {
            onTranslateClick();
        } else if (dialog.header === 'AI Rephrase') {
            onRewriteClick();
        } else {
            onGrammerCheckClick();
        }
    }

    function updateIndex() {
        let element: HTMLInputElement = document.getElementById('numeric')! as HTMLInputElement;
        let editableDiv = document.getElementById("e-de-editable-div");
        let text: string = editableDiv!.innerHTML;
        if (outList.length > 0 && outList.indexOf(text) !== -1) {
            element.value = (outList.indexOf(text) + 1).toString();
        } else if (element) {
            element.value = '0';
        }
    }

    //convertion
    async function onInsertContent(): Promise<void> {
        let response: string = editableDiv!.innerHTML;
        let http = new XMLHttpRequest();
        let url: string = container.current!.serviceUrl + 'SystemClipboard';
        http.open('POST', url, true);
        http.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
        http.onreadystatechange = () => {
            if (http.readyState === 4) {
                if (http.status === 200 || http.status === 304) {
                    container.current!.documentEditor.editor.paste(http.responseText);
                    container.current!.documentEditor.editor.onEnter();
                    clearContent();
                    dialog.hide();
                }
            }
        };
        let sfdt: any = {
            content: response,
            type: '.Html',
        };
        http.send(JSON.stringify(sfdt));
    }

    //clear

    function clearContent(): void {
        editableDiv!.innerHTML = '';
        questionDiv!.innerText = '';
    }

    return (
        <>
            <div className="description-container e-card">
                <div className='e-card-content'>
                    <p>This sample showcases the Smart Editor's capabilities in the Syncfusion React Document Editor. It enhances document editing by rewriting, checking grammar, and translating text. Users can refine content through selection context, improving writing quality with grammar corrections, paraphrasing for readability, and translating into different languages - all within the editor. Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/document-editor/Readme.md">here</a>.
                    </p>
                </div>
            </div>
            <div id='container' style={{ height: "100%", width: "100%" }}>
                <div id="documenteditor_titlebar" className="e-de-ctn-title"></div>
                <DocumentEditorContainerComponent
                    ref={container}
                    id='DocumentEditor'
                    style={{ height: "99%", width: "100%" }}
                    enableToolbar={true}
                    height='99%'
                    width='100%'
                    serviceUrl='https://services.syncfusion.com/react/production/api/documenteditor/'
                >
                    <DialogComponent
                        id='dialog'
                        ref={(dialogRef: DialogComponent) => dialog = dialogRef as DialogComponent}
                        header='AI Rephrase'
                        showCloseIcon={true}
                        content={document.getElementById("splitter") as HTMLElement | undefined}
                        buttons={[
                            {
                                click: () => {
                                    onInsertContent();
                                },
                                buttonModel: {
                                    isPrimary: true,
                                    content: 'Replace'
                                }
                            },
                            {
                                click: () => {
                                    clearContent();
                                    dialog.hide();
                                },
                                buttonModel: {
                                    content: 'Cancel',
                                    cssClass: 'e-flat'
                                }
                            }
                        ]}
                        visible={false}
                        target={document.getElementById("DocumentEditor") as HTMLElement | undefined}
                        width='50%'
                        height='auto'
                        isModal={true}
                        close={onclose}
                        beforeOpen={onBeforeOpen}
                        open={onOpen}
                    >
                        <SplitterComponent
                            id="splitter"
                            height='auto'
                            paneSettings={[
                                { size: 'auto', collapsible: true },
                                { size: 'auto', collapsible: true }
                            ]}
                            orientation='Vertical'
                            width='100%'
                        >
                            <div id="e-de-qus-parent">
                                <div id="e-de-qus-div"
                                    ref={question => questionDiv = question as HTMLDivElement}
                                ></div>
                                <ToolbarComponent id="e-de-qus-toolbar">
                                    <ItemsDirective>
                                        <ItemDirective prefixIcon='e-icons e-chevron-left' align='Center' click={moveToPreviousPara} />
                                        <ItemDirective prefixIcon='e-icons e-chevron-right' align='Center' click={moveToNextPara} />
                                    </ItemsDirective>

                                </ToolbarComponent>
                            </div>
                            <div id="e-de-editable-div"
                                ref={editable => editableDiv = editable as HTMLDivElement}
                                contentEditable="true" style={{ height: "85px", padding: "5px" }}></div>
                        </SplitterComponent>
                        <ToolbarComponent id="e-d-toolbar"
                            ref={(toolbarObj: ToolbarComponent) => toolbar = toolbarObj as ToolbarComponent}
                            created={onToolbarCreated}>
                            <ItemsDirective>
                                {/* 1st Group */}
                                <ItemDirective prefixIcon='e-icons e-chevron-left' align='Left' click={moveToPrevious} />
                                <ItemDirective type='Input' align='Left' cssClass='page-count'
                                    template={() => <div>
                                        <input type='text' id='numeric' style={{ width: '20px', paddingLeft: '10px' }} />
                                        <span className="total-page"> of 3 </span>
                                    </div>}
                                />
                                <ItemDirective prefixIcon='e-icons e-chevron-right' align='Left' click={moveToNext} />
                                <ItemDirective text='Rewrite' align='Right' click={onRewriteClick} />
                                <ItemDirective prefixIcon='e-icons e-settings' align='Right' click={onSettingsClick} />

                                {/* 2nd Group */}
                                <ItemDirective prefixIcon='e-icons e-close' align='Left' click={onCloseSecndaryToolbar} />
                                <ItemDirective type='Input' align='Left'
                                    template={() => <ComboBoxComponent width='125px' change={onToneChange} value={toneValue} dataSource={toneList} popupWidth='125px' showClearButton={false} readonly={false} />}
                                />
                                <ItemDirective type='Input' align='Left'
                                    template={() => <ComboBoxComponent width='200px' change={onFormatChange} value={formatValue} dataSource={formatValueList} popupWidth='200px' showClearButton={false} readonly={false} />}
                                />
                                <ItemDirective type='Input' align='Left'
                                    template={() => <ComboBoxComponent width='100px' change={onLengthChange} value={lengthValue} dataSource={lengthList} popupWidth='100px' showClearButton={false} readonly={false} />}
                                />
                                <ItemDirective text='Rewrite' align='Right' click={onRewriteClick} />

                                {/* 3rd Group */}
                                <ItemDirective type='Input' align='Left'
                                    template={() => <ComboBoxComponent width='160px' change={onLanguageChange} value='French' dataSource={languageList} popupWidth='160px' showClearButton={false} readonly={false} />}
                                />
                                <ItemDirective text='Translate' align='Right' click={onTranslateClick} />

                                {/* 4th Group */}
                                <ItemDirective type='Input' align='Left'
                                    template={() => <MultiSelectComponent width='250px' change={ValueChangeHandler} dataSource={grammer} fields={{ text: 'name', value: 'name' }} placeholder="e.g. Spelling Errors" mode='CheckBox' showSelectAll={true} selectAllText="Select All" showDropDownIcon={true} enableSelectionOrder={true} filterBarPlaceholder="Search grammar suggestion">
                                        <Inject services={[CheckBoxSelection]} />
                                    </MultiSelectComponent>}
                                />
                                <ItemDirective text='Rewrite' align='Right' click={onGrammerCheckClick} />
                            </ItemsDirective>
                        </ToolbarComponent>
                    </DialogComponent>
                    <Inject services={[Toolbar]} />
                </DocumentEditorContainerComponent >
            </div >
        </>
    )
}

export default SmartEditor

// angular/src/app/document-editor/smart-editor/smart-editor.component.ts
import { Component, ViewChild, OnInit,contentChildren } from '@angular/core';
import { DocumentEditorContainerAllModule, DocumentEditorContainerComponent } from '@syncfusion/ej2-angular-documenteditor';
import { BeforeOpenCloseCustomContentMenuEventArgs, CustomContentMenuEventArgs, CustomToolbarItemModel } from '@syncfusion/ej2/documenteditor';
import { getAzureChatAIRequest } from '../../ai-models/ai-models';
import { ClickEventArgs, MenuItemModel } from '@syncfusion/ej2/navigations';
import { DialogAllModule, ButtonPropsModel, DialogComponent, ButtonProps, showSpinner, hideSpinner,createSpinner } from '@syncfusion/ej2-angular-popups';
import { SplitterAllModule } from '@syncfusion/ej2-angular-layouts';
import { MultiSelectAllModule, ChangeEventArgs, ComboBoxAllModule, MultiSelectChangeEventArgs } from '@syncfusion/ej2-angular-dropdowns';
import { TitleBar } from './title-bar';
import { ToolbarAllModule, ToolbarComponent } from '@syncfusion/ej2-angular-navigations';
import { create } from '@syncfusion/ej2-angular-grids';

interface Message {
  role: string;
  content: string;
}

interface AzureAIRequestOptions {
  messages: Message[];
  model: string;
}
@Component({
  selector: 'app-smart-editor',
  standalone: true,
  imports: [DocumentEditorContainerAllModule,
    DialogAllModule, SplitterAllModule, ToolbarAllModule, ComboBoxAllModule, MultiSelectAllModule],
  templateUrl: './smart-editor.component.html',
  styleUrl: './smart-editor.component.css'
})
export class SmartEditorComponent  {
  @ViewChild('container', { static: true }) container!: DocumentEditorContainerComponent;
  @ViewChild('dialog', { static: true }) dialog!: DialogComponent;
  @ViewChild('qdiv', { static: false }) questionDiv!: any;
  @ViewChild('editable', { static: false }) editableDiv!: any;
  @ViewChild('toolbar', { static: false }) toolbar!: ToolbarComponent;
  // Variable declateion
  titleBar!: TitleBar;
  outList: string[] = [];
  translateValue: string = 'French';
  grammerList: string[] = [];
  toneValue: string = 'Professional';
  formatValue: string = 'Paragraph';
  lengthValue: string = 'Medium';
  menuItems: MenuItemModel[] = [
    {
      text: 'Rewrite',
      id: 'rewrite',
      iconCss: 'e-icons e-edit'
    },
    {
      text: 'Translate',
      id: 'translate',
      iconCss: 'e-icons e-transform-right'
    },
    {
      text: 'Grammar',
      id: 'grammer',
      iconCss: 'e-icons e-redaction'
    },
  ];
  buttonSettings: ButtonPropsModel[] = [
    {
      'click': () => {
        this.onInsertContent();
      },
      buttonModel: {
        isPrimary: true,
        content: 'Replace'
      }
    },
    {
      'click': () => {
        this.clearContent();
        this.dialog.hide();
      },
      buttonModel: {
        content: 'Cancel',
        cssClass: 'e-flat'
      }
    }
  ];
  toneList: string[] = ['Professional', 'Friendly', 'Instructional', 'Marketing', 'Academic', 'Legal', 'Technical', 'Narrative', 'Direct'];
  formatValueList: string[] = ['Paragraph', 'Blog post', 'Technical Documentation', 'Report', 'Research Papers', 'Tutorial', 'Meeting Notes'];
  lengthList: string[] = ['Short', 'Medium', 'Long'];
  grammer: { [key: string]: Object }[] = [
    { id: 'SVA', name: 'Subject-Verb Agreement' },
    { id: 'TC', name: 'Tense Consistency' },
    { id: 'PA', name: 'Pronoun Agreement' },
    { id: 'CU', name: 'Comma Usage' },
    { id: 'PS', name: 'Parallel Structure' },
    { id: 'MM', name: 'Misplaced Modifiers' },
    { id: 'DM', name: 'Dangling Modifiers' },
    { id: 'WC', name: 'Word Choice' },
    { id: 'R', name: 'Redundancy' },
    { id: 'UA', name: 'Use of Articles' },
    { id: 'PM', name: 'Punctuation Marks' },
    { id: 'APC', name: 'Apostrophes for Possessives and Contractions' },
    { id: 'SE', name: 'Spelling Errors' }
  ];
  languageList: string[] = ['Simplified Chinese', 'Spanish', 'French', 'Arabic', 'Portuguese', 'Russian', 'Urdu', 'Indonesian', 'German', 'Japanese'];


  documenedContainercreated(): void {
    let sfdt: string = '{\"sfdt\":\"UEsDBAoAAAAIAH1d+FjMBUJu5wgAAM49AAAEAAAAc2ZkdO1b3W4jtxV+FXZ6kQaQDUuy5Z+bINnGSYEgDbIuFkWwF5wZjkSYQ05JjrTKYm/6Mn2EPlZfod8hR9JIlkb2xrHl3RjYJUVyhufnOz88lN4npvKylL+K10Xukytva9FLnMiSq1/eJ2grm1y9T6pZcjXqD3pJNUmuzi/RUSU6aG3T+qZNmzYvquTqBK0RsTPJk6vhqJcUTZvKMJxip+RHMfuJj0WC94+1w8DXlqcyw2edGYWBfi8R/5qFVqU+C0/GmV/efsBLArVVQaSmuXXUemz7HnPKx9aOY5s2nyexmVKD1qV8yT1fdb0GNd8Lnks9ZgMQpGTRPJGF7Qr3K8i6AF/4mNzIUjgGdtjPpuQ6oWFidOsE3zGuC7FjZusESJGB/wMiyCtIP/mHVia7Jcm9Mkrx1FjupdFX7G9lpUQptN+Ymwr2bS7DKN5ygBxJzf5pahuoNDb58Jao/N1w96OxJVfsL29E+uVO6A226n+wJHlN9GzCHUtFZkrBuGZSezG22KLi1jNTMOJtZuwty2rlayt6TLhKZJIrNcdqxmlW5Ww2EVbc1dFqVytK40V8l2y2JLVKnVnBHbp4IcZKo48BBz6WWmAVLeGpEsyb+KyhPXOT1YQWoqBzT66O4Mw6CZtJP2Fe8LLkHjoGQNHmjGfWOMf8RLCxMqk4ZjcT7r+II5WZCUviydagKiJU//QiYLBmclv5YEWtMwIJV9IHbc8JDiJAnWWAixVTo2pagngRJDPjc1rVJXCu8/giEnpUqjdjgaftMXszCR1a8AUANbOREo6tKmN9j+WWF81QZU1lHFc9RuRA2dv9RGvnrsnKCgdpBKvoBV4QcQLjgB7xzIjwzByFnQRzsoRJcC1M7QDdACNDtLsgGuexrFSE4o5Ngxy6wAnpFMrMwt6pMc4T13kNtUxB2vHvjbRFoBvuhNnw0ALd8BDCwpvJfHsY++qlhYiWO4DPNzPHCPYSvoPVjsC+tI6VV143jR5BdirzaLRdFqi4L0A+w39s5buzdrwiN4zwUcAEEY2w0vlABGyNbAXhCQlibZE7usYlkJ309vmjjmmhJ1xn9DoEp1rLLMZNjkA1ji6sFGUKIo7ZN/PgzojRhUeL8SqEN7EUUG+PS+iaJt/Cp0bmbIo9iZLMaG+NQlR1tXCQgEL6rslFkRPTAsGMBJry7PYIvB7hA1yVKLlUWE3cC+3q7ugtsNncwJdB9tiSXuw4dFNB0M/qhNLFUsC54Mqht88NpOQFmofS1mNP7a5eGOkRCN8jFsHil8nDS/ZyNyFn5fjnCN94H7KX4NDkkr3tidF6KnTM/q4pJ6xqxS28gZ+YTo8CG+qYxfZwrHAa27f2BqYOc65UjRQZlsj9Imun9NVR0iHcMiOJZL6Tbl9utGClYwnk5UQgAEKaV/CEdAiIzl0sXDJIqLMJw6li5cEb2nvBhUKqjdvRxsui8af7RNIxeytExVYOKnonZUx1/CJQ+LVCBNNByRQryf2Tj09rqZo82cz0PRN0CGoNl53K7Iah1EjtpwFRPuxVVxTIhIWgyUQQFHOEtHaYbofHVPiZEDrmCL2VQe1BoZtwG/IEwKMStkRMa4W4BjdurrNwaAENFOeboxrQSAu1yOj8Fjb+IzR9RqHpG6FFIb2jc/nWqPSpHMs3DuIGckEKzOHw4YYt2QSJIG3E0aMSi6pz2WF2enz1GMLBaTeWch8sJTR5qOEqqbRB7yPEhjgk8s0sHe5icTZ46RzGQhlYbFcAYv5eIIxKnHzmL5zHnzdThsBegSMMnV5eOHOvlxWhnK3VdayAOjEorDVg6o+Q9dmErO+EZ689t5Sw3Jicz19G6RhmmseyaBkr4a1yLh06toatr9gNv401iUJa55nzyNvTOU4nlTIh66O5jig1RW5oatecQEKKGA5B6E+5VOGagCodi+NQfGWrWnQ3QV6Um/fUY0zlu5bQplShhlSOSo4g7JqqOB3UcpFRXMbO6yl9b1d0pxNUdzUG7/KI8y4Uy7rWtQryoc4eK9iLXUW7aP0oqXJzM6ucD56yDbm7YNsDsm/L1PJM7LxvaaJ7Ha4UmYZxVTgFyFCzlzC33UjsPvbsLddH7ARLfQsJRJ7etlxo40c2HVG/cUSvcFpLrYRA6kZK8d6bx1vxeJeNR8gLxYeCP1o9xrOWr+JrUwtX1B5ZGwArvz1+gj7btEXT+kh96kLDY7MBB6PimpVgbmnXRX+ml/1ZtvBaK8wUrqHIFyp2cj+Lsby5/xe6iCIEsQlYd01blHH/Kjb5xJeRkqKIBCJnrBpVzH3aUElySOi7CH++Dn8kOswHxK7Bunn5b5PqpmXod6stCI/tyN1/rE33qpK+4NHW5fHJ+WV/NBqdnZyfD04uT8/XldvfFVBG69BnP8jxxJNmgnwH12enl6NkA82rReuYbo1vGY7f/Vgpp1OO7NWE2yjM/jMT/FdR8Fp59hO3HLGrmrBro/2S5B3Ta6R/2ORv8GQ4eRhMBvvuEg8LJoPdMBkeGEzauf0han64M+PsFGT/eng+Gj695oe7Nf/kBN9T86cHqvnTu5pfHr4O0OZPt2n+mQi+p+bPDlTzZ1ts/vAUfrbV1A9Rz6MD1fPoQXp+Lpc+eqCen8+Tnx+ons8/zpM/l8LPP9aTP5/mLw5U8xe7sreT47NOUQ7D39Pr/mJ3/vYMJN9T+5cHqv3LLrs/aBhcdruAA8aDsI8Dhu31uLtVp7sibahYEHVtjH9+ohoqFkRt3Gk8AmlkHWeRwrNd9ym7r052AbOhkGrFKla++fJO0dAPl3rNHSOtwMPrK6bqTrH8pIHs63mZGrUEZ+tjRGVroP35UWrB4Rdc1Dnqr8UH6X4YN1XWjKyvuTmtItlUqU3+9+//0g+8QlGV6rQ2rnfkoVo1+GCUprZSWLpDW9ngxlhjgRujdwYfhevzwQN5Nffl9A08Fnktt+RzfSRyuT62MfQoHPZPHq7O/9yXyecEbP/09PPBaf/i5FMH6qA/+jSBOjgbfD5AHVxcfOpAHQ5OHxOo4fY5K2PeYGOTvYutLMcubPN/UEsBAhQACgAAAAgAfV34WMwFQm7nCAAAzj0AAAQAAAAAAAAAAAAAAAAAAAAAAHNmZHRQSwUGAAAAAAEAAQAyAAAACQkAAAAA\"}';
    this.container.documentEditor.open(sfdt);
    this.titleBar = new TitleBar(document.getElementById('documenteditor_titlebar')!, this.container.documentEditor, true);
    this.container.documentEditor.documentName = 'Getting Started';
    this.titleBar.updateDocumentTitle();
    this.container.documentEditor.contextMenu.addCustomMenu(this.menuItems, false);
    createSpinner({ target: document.getElementById('dialog') as HTMLElement });
  }
// Context menu AI click event triggers
  onRewrite() {
    this.dialog.header = 'AI Rephrase';
    this.dialog.show();
    this.questionDiv.nativeElement.innerText = this.container.documentEditor.selection.text;
    this.onChangeToolbarVisibility(true, false, false);
    this.onRewriteClick();
  }

  onTranslate() {
    this.dialog.header = 'AI Translate';
    this.dialog.show();
    this.questionDiv.nativeElement.innerText = this.container.documentEditor.selection.text;
    this.onChangeToolbarVisibility(false, true, false);
    this.onTranslateClick();
  }

  onGrammerCheck() {
    this.dialog.header = 'Grammer';
    this.dialog.show();
    this.questionDiv.nativeElement.innerText = this.container.documentEditor.selection.text;
    this.onChangeToolbarVisibility(false, false, true);
    this.onGrammerCheckClick();
  }

  onCustomContextMenuSelect(args: CustomContentMenuEventArgs): void {
    {
      let item: string = args.id;
      let id: string = this.container.element.id;
      switch (item) {
        case id + '_editorrewrite':
          this.onRewrite();
          break;
        case id + '_editortranslate':
          this.onTranslate();
          break;
        case id + '_editorgrammer':
          this.onGrammerCheck();
          break;
      }
    };
  }
  // Dialog events
  onBeforeOpen(): void {
    this.onChangeToolbarVisibility(true, false, false);
  }
  onclose(): void {
    this.clearContent();
  }
  onOpen(args: any): void {
    args.preventFocus = true;
  }
  // toolbar events 
  async onToolbarCreated(): Promise<void> {
    this.updateIndex();
  }
  updateIndex() {
    let element: HTMLInputElement = document.getElementById('numeric')! as HTMLInputElement;
    let text: string = this.editableDiv.nativeElement.innerHTML;
    if (this.outList.length > 0 && this.outList.indexOf(text) !== -1) {
      element.value = (this.outList.indexOf(text) + 1).toString();
    } else {
      element.value = '0';
    }
  }
// Toolbar selection

  onChangeToolbarVisibility(showPryItem: boolean, showTranslateItem: boolean, showGrammerItem: boolean) {
    let isPrimary: boolean = false;
    let isSecondary: boolean = true;
    let isTranslate: boolean = false;
    let isGrammer: boolean = false;
    if (showPryItem) {
      isPrimary = true;
      isSecondary = false;
      isTranslate = false;
      isGrammer = false;
    }
    if (showTranslateItem) {
      isPrimary = false;
      isSecondary = false;
      isTranslate = true;
      isGrammer = false;
    }
    if (showGrammerItem) {
      isPrimary = false;
      isSecondary = false;
      isTranslate = false;
      isGrammer = true;
    }
    for (let i = 0; i < 5; i++) {
      this.toolbar.items[i].visible = isPrimary;
      this.toolbar.items[i + 5].visible = isSecondary;
    }
    this.toolbar.items[10].visible = isTranslate;
    this.toolbar.items[11].visible = isTranslate;
    this.toolbar.items[12].visible = isGrammer;
    this.toolbar.items[13].visible = isGrammer;
  }
// Move to previous parameter 
  moveToPreviousPara() {
    this.editableDiv.nativeElement.innerHTML = '';
    this.container.documentEditor.selection.moveToParagraphEnd();
    this.container.documentEditor.selection.moveToNextLine();
    this.container.documentEditor.selection.selectParagraph();
    this.questionDiv.nativeElement.innerText = this.container.documentEditor.selection.text;
    if (this.dialog.header === 'AI Translate') {
      this.onTranslateClick();
    } else if (this.dialog.header === 'AI Rephrase') {
      this.onRewriteClick();
    } else {
      this.onGrammerCheckClick();
    }
  }
// Move to Next parameter 
  moveToNextPara() {
    this.editableDiv.nativeElement.innerHTML = '';
    this.container.documentEditor.selection.moveToParagraphEnd();
    this.container.documentEditor.selection.moveToNextLine();
    this.container.documentEditor.selection.selectParagraph();
    this.questionDiv.nativeElement.innerText = this.container.documentEditor.selection.text;
    if (this.dialog.header === 'AI Translate') {
      this.onTranslateClick();
    } else if (this.dialog.header === 'AI Rephrase') {
      this.onRewriteClick();
    } else {
      this.onGrammerCheckClick();
    }
  }
// Move to Next parameter 
  moveToNext() {
    let text: string = this.editableDiv.nativeElement.innerHTML;
    let index: number = this.outList.indexOf(text);
    if (index + 1 < this.outList.length) {
      this.editableDiv.nativeElement.innerHTML = this.outList[index + 1];
      this.updateIndex();
    }
  }
// Move to Next parameter 
  moveToPrevious() {
    let text: string = this.editableDiv.nativeElement.innerHTML;
    let index: number = this.outList.indexOf(text);
    if (index - 1 >= 0) {
      this.editableDiv.nativeElement.innerHTML = this.outList[index - 1];
      this.updateIndex();
    }
  }
  // Settings click event triggers
  onSettingsClick() {
    this.onChangeToolbarVisibility(false, false, false);
  }
  onCloseSecndaryToolbar() {
    this.onChangeToolbarVisibility(true, false, false);
  }

  onToneChange(args: ChangeEventArgs): void {
    this.toneValue = args.value as string;
  }
  onFormatChange(args: ChangeEventArgs): void {
    this.formatValue = args.value as string;
  }
  onLengthChange(args: ChangeEventArgs): void {
    this.lengthValue = args.value as string;
  }
  onLanguageChange(args: ChangeEventArgs): void {
    this.translateValue = args.value as string;
  }
  ValueChangeHandler(args: MultiSelectChangeEventArgs): void {
    this.grammerList = args.value as string[];
  }
// Rewrite the content
  async onRewriteClick() {
    showSpinner(document.getElementById('dialog') as HTMLElement);
    let text: string = this.questionDiv.nativeElement.innerText;
    const options: AzureAIRequestOptions = {
      messages: [
        { role: "system", content: `You are a helpful assistant. Your task is to analyze the provided text and rephrase it. Please adjust the text to reflect a tone of '${this.toneValue}', formatted in '${this.formatValue}' style, and maintain a length of '${this.lengthValue}'. Always respond in proper HTML format, excluding <html>, <head>, and <body> tags.` },
        { role: "user", content: text }
      ],
      model: "gpt-4",
    };
    await this.onGenerate(options);
    hideSpinner(document.getElementById('dialog') as HTMLElement);
  }
// Translate to other language
  async onTranslateClick() {
    showSpinner(document.getElementById('dialog') as HTMLElement);
    let text: string = this.questionDiv.nativeElement.innerText;
    const options: AzureAIRequestOptions = {
      messages: [
        { role: "system", content: `You are a helpful assistant. Your task is to translate the provided text into '${this.translateValue}'. Always respond in proper HTML format, excluding <html> and <head> tags.` },
        { role: "user", content: text }
      ],
      model: "gpt-4",
    };
    await this.reframeContent(options);
    hideSpinner(document.getElementById('dialog') as HTMLElement);
  }
// Grammer check
  async onGrammerCheckClick() {
    showSpinner(document.getElementById('dialog') as HTMLElement);
    let value: string = '';
    let systemPrompt: string = '';
    if (this.grammerList.length > 0) {
      this.grammerList.forEach((item) => {
        value += item + ', ';
      });
      systemPrompt = `You are a helpful assistant. Your task is to analyze the provided text and perform the following grammar checks: ${value}. Please ensure that the revised text reflects these corrections. Always respond in proper HTML format, but do not include <html>, <head>, or <body> tags.`;
    } else {
      systemPrompt = "You are a helpful assistant. Your task is to analyze the provided text, check for and correct any grammatical errors, and rephrase it. Always respond in proper HTML format, but do not include <html>, <head>, or <body> tags.";
    }
    let text: string = this.questionDiv.nativeElement.innerText;
    const options: AzureAIRequestOptions = {
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: text }
      ],
      model: "gpt-4",
    };
    await this.reframeContent(options);
    hideSpinner(document.getElementById('dialog') as HTMLElement);
  }
  //AI convertion

  async onInsertContent(): Promise<void> {
    let response: string = this.editableDiv.nativeElement.innerHTML;
    let http = new XMLHttpRequest();
    let url: string = this.container.serviceUrl + 'SystemClipboard';
    http.open('POST', url, true);
    http.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
    http.onreadystatechange = () => {
      if (http.readyState === 4) {
        if (http.status === 200 || http.status === 304) {
          this.container.documentEditor.editor.paste(http.responseText);
          this.container.documentEditor.editor.onEnter();
          this.clearContent();
          this.dialog.hide();
        }
      }
    };
    let sfdt: any = {
      content: response,
      type: '.Html',
    };
    http.send(JSON.stringify(sfdt));
  }
  
  async onGenerate(options: AzureAIRequestOptions): Promise<void> {
    this.outList = [];
    for (let i = 0; i < 3; i++) {
      const response = await getAzureChatAIRequest(options);
      if (response && this.outList.indexOf(response) === -1) {
        this.outList.push(response);
      } else {
        i--;
      }
    }
    if (this.outList.length > 0) {
      this.editableDiv.nativeElement.innerHTML = this.outList[0];
      this.updateIndex();
    }
  }
// Generate refined text
  async reframeContent(options: AzureAIRequestOptions): Promise<void> {
    const response = await getAzureChatAIRequest(options);
    if (response) {
      this.editableDiv.nativeElement.innerHTML = response;
    }
  }
  clearContent(): void {
    this.editableDiv.nativeElement.innerHTML = '';
    this.questionDiv.innerText = '';
  }
}

<h2 style="text-align: center;">Smart Editor</h2>
<div class="description-container e-card">
  <div class='e-card-header-title' style="font-weight: 600;">AI-Powered Document Editor</div>
  <div class='e-card-content '>
    <!--!-->
    <p>
      This sample showcases the Smart Editor's capabilities in the Syncfusion Angular Document Editor. It enhances document
      editing by rewriting, checking grammar, and translating text. Users can refine content through selection context,
      improving writing quality with grammar corrections, paraphrasing for readability, and translating into different
      languages—all within the editor.
    </p>
  </div>
</div>
<div id='container' style="height: 100%;width: 100%;">
  <div id="documenteditor_titlebar" class="e-de-ctn-title"></div>
  <ejs-documenteditorcontainer #container id='DocumentEditor'  [enableToolbar]="true"
    height="98vh" width="100%" serviceUrl="https://services.syncfusion.com/js/production/api/documenteditor/"
    (created)="documenedContainercreated()" (customContextMenuSelect)="onCustomContextMenuSelect($event)">

  </ejs-documenteditorcontainer>
  <ejs-dialog #dialog id="dialog" header="AI Rephrase" [showCloseIcon]="true"  [buttons]="buttonSettings"
    [visible]="false" target="#DocumentEditor" width="50%" height="auto" [isModal]="true" (close)="onclose()"
    (beforeOpen)="onBeforeOpen()" (open)="onOpen($event)">
    <ng-template #content>
      <!-- help: https://ej2.syncfusion.com/angular/documentation/splitter/split-panes/#horizontal-layout -->
      <ejs-splitter height="auto" orientation="Vertical" width="100%">
        <e-panes>
          <e-pane size="auto" [collapsible]='true'>
            <ng-template #content>
              <div>
              <div id="e-de-qus-parent">
                <div #qdiv id="e-de-qus-div"></div>
                <ejs-toolbar id="e-de-qus-toolbar" prefixIcon="e-icons e-chevron-left">
                  <e-items>
                    <e-item prefixIcon="e-icons e-chevron-left" align="Center" (click)="moveToPreviousPara()"></e-item>
                    <e-item prefixIcon="e-icons e-chevron-right" align="Center" (click)="moveToNextPara()"></e-item>

                  </e-items>
                </ejs-toolbar>
                <div id="e-de-qus-toolbar"></div>
              </div>
            </div>
            </ng-template>
          </e-pane>
          <e-pane  size="auto" [collapsible]='true'>
            <ng-template #content>
              <div>
                <div #editable id="e-de-editable-div" contenteditable="true" style="height: 100px; padding: 5px;background: #f9fafb;"></div>
              </div>
            </ng-template>
          </e-pane>

        </e-panes>
      </ejs-splitter>
      <ejs-toolbar #toolbar id="toolbar" (created)="onToolbarCreated()">
        <!-- 1st Toolbar -->
        <e-items>
          <e-item prefixIcon="e-icons e-chevron-left" (click)="moveToPrevious()"></e-item>
          <e-item type="Input" align="Left" cssClass="page-count">
            <ng-template #template>
              <div>
                <input type="text" id="numeric" style="width: 20px; padding-left: 10px;">
                <span class="total-page"> of 3 </span>
              </div>
            </ng-template>
          </e-item>
          <e-item prefixIcon="e-icons e-chevron-right" (click)="moveToNext()"></e-item>
          <e-item text="Rewrite" align="Right" (click)="onRewriteClick()"></e-item>
          <e-item prefixIcon="e-icons e-settings" (click)="onSettingsClick()"></e-item>

          <!-- 2nd Toolbar -->

          <e-item prefixIcon="e-icons e-close" (click)="onCloseSecndaryToolbar()"></e-item>
          <e-item type="Input" align="Left">
            <ng-template #template>
              <ejs-combobox [width]="'125px'" (change)="onToneChange($event)" [value]="toneValue"
                [dataSource]="toneList" [popupWidth]="'125px'" [showClearButton]="false"
                [readonly]="false"></ejs-combobox>
            </ng-template>
          </e-item>
          <e-item type="Input" align="Left">
            <ng-template #template>
              <ejs-combobox [width]="'200px'" (change)="onFormatChange($event)" [value]="formatValue"
                [dataSource]="formatValueList" [popupWidth]="'200px'" [showClearButton]="false"
                [readonly]="false"></ejs-combobox>
            </ng-template>
          </e-item>
          <e-item type="Input" align="Left">
            <ng-template #template>
              <ejs-combobox [width]="'100px'" (change)="onLengthChange($event)" [value]="lengthValue"
                [dataSource]="lengthList" [popupWidth]="'100px'" [showClearButton]="false"
                [readonly]="false"></ejs-combobox>
            </ng-template>
          </e-item>
          <e-item text="Rewrite" (click)="onRewriteClick()"></e-item>

          <!-- 3rd Toolbar -->

          <e-item type="Input" align="Left">
            <ng-template #template>
              <ejs-combobox [width]="'160px'" (change)="onLanguageChange($event)" [value]="'French'"
                [dataSource]="languageList" [popupWidth]="'160px'" [showClearButton]="false"
                [readonly]="false"></ejs-combobox>
            </ng-template>
          </e-item>
          <e-item text="Translate" (click)="onTranslateClick()"></e-item>


          <!-- 4th Toolbar -->

          <e-item type="Input" align="Left">
            <ng-template #template>
              <ejs-multiselect [width]="'250px'" (change)="ValueChangeHandler($event)" [dataSource]="grammer"
                [fields]="{ text: 'name', value: 'name' }" placeholder="e.g. Spelling Errors" mode="CheckBox"
                showSelectAll="true" selectAllText="Select All" showDropDownIcon="true" enableSelectionOrder="true"
                filterBarPlaceholder="Search grammar suggestion"></ejs-multiselect>
            </ng-template>
          </e-item>
          <e-item text="Rewrite" align="Right" (click)="onGrammerCheckClick()"></e-item>
        </e-items>
      </ejs-toolbar>
    </ng-template> 
  </ejs-dialog>

</div>
