// angular/src/app/diagram/smart-umlSequenceDiagram/smart-umlSequenceDiagram.component.ts
import { Component, ViewChild } from '@angular/core';
import {
  DiagramComponent, DiagramModule, NodeModel,
  IScrollChangeEventArgs, FileFormats, DiagramTools, PrintAndExportService,
  IExportOptions, SnapConstraints,
} from '@syncfusion/ej2-angular-diagrams';
import {UmlSequenceParticipant, UmlSequenceFragment, UmlSequenceDiagramModel} from '@syncfusion/ej2-diagrams';
import { ToolbarModule, ClickEventArgs } from '@syncfusion/ej2-angular-navigations';
import { TextBoxComponent, TextBoxModule } from '@syncfusion/ej2-angular-inputs';
import { ButtonComponent, ButtonModule, FabModule } from '@syncfusion/ej2-angular-buttons';
import { UploaderModule, InputEventArgs } from '@syncfusion/ej2-angular-inputs';
import { DialogComponent, DialogModule } from '@syncfusion/ej2-angular-popups';
import { DropDownButtonComponent, DropDownButtonModule, MenuEventArgs } from '@syncfusion/ej2-angular-splitbuttons';
import { convertTextToUmlSequenceDiagram } from './ai-umlSequenceDiagram';
import { exportItems, sequenceModel, zoomMenuItems } from './dataSource';

@Component({
  selector: 'app-smart-uml-sequence-diagram',
  providers: [PrintAndExportService],
  templateUrl: './smart-umlSequenceDiagram.component.html',
  styleUrls: ['./smart-umlSequenceDiagram.component.css'],
  standalone: true,
  imports: [DiagramModule,ToolbarModule, ButtonModule, FabModule, UploaderModule, DialogModule, DropDownButtonModule, TextBoxModule],
})
export class SmartUmlSequenceDiagramComponent {
  @ViewChild('diagram', { static: true }) public diagram!: DiagramComponent;
  @ViewChild('dialog', { static: true }) public dialog!: DialogComponent;
  @ViewChild('msgBtn1', { static: true }) public msgBtn1!: ButtonComponent;
  @ViewChild('msgBtn2', { static: true }) public msgBtn2!: ButtonComponent;
  @ViewChild('msgBtn3', { static: true }) public msgBtn3!: ButtonComponent;
  @ViewChild('textBox', { static: true }) public textBox!: TextBoxComponent;
  @ViewChild('sendButton', { static: true }) public sendButton!: ButtonComponent;
  public asyncSettings: Object = {
    saveUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Save',
    removeUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Remove'
  };
  public zoomMenuItems: any = zoomMenuItems;
  public exportItems: any = exportItems;
  public zoomContent: any;
  public diagramTools: DiagramTools = DiagramTools.ZoomPan;
  public sequenceModel: UmlSequenceDiagramModel = sequenceModel;
  public nodes: NodeModel[] = [{ id: 'content', offsetX: 100, offsetY: 100 }];
  ngOnInit(): void {
    document.addEventListener('keypress', (event) => {
      if (event.key === 'Enter' && document.activeElement === (this.textBox as any).element.nativeElement) {
        if ((this.textBox as any).value !== '') {
          (this.dialog as any).hide();
          convertTextToUmlSequenceDiagram((this.textBox as any).value, this.diagram);
        }
      }
    });
    this.zoomContent = Math.round(this.diagram.scrollSettings.currentZoom! * 100) + ' %';
  }

  showDialog() {
    this.dialog.show();
  }

  onSendClick() {
    this.dialog.hide();
    convertTextToUmlSequenceDiagram((this.textBox as any).value, this.diagram);
  }
  diagramCreated() {
    (this.diagram as any).model = this.sequenceModel;
    this.diagram.updateFromModel();
  }
  onBtnClick(msg: any) {
    this.dialog.hide();
    convertTextToUmlSequenceDiagram(msg, this.diagram);
  }

  onScrollChange(args: IScrollChangeEventArgs) {
    if (args.panState !== 'Start') {
      let zoomCurrentValue: any = (document.getElementById("btnZoomIncrement") as any).ej2_instances[0];
      zoomCurrentValue.content = Math.round(this.diagram.scrollSettings.currentZoom! * 100) + ' %';
    }
  }

  public snapSettings: any = { constraints: SnapConstraints.None };
  // Configure node defaults for UML diagrams
  public getNodeDefaults(node: NodeModel): NodeModel {
    // participant node
    if (node.data instanceof UmlSequenceParticipant) {
      if (!((node!.data! as UmlSequenceParticipant).isActor)) {
        if (node.annotations && node.annotations[0] && node.annotations[0].style) {
          node.annotations[0].style.color = 'white';
        }
      }
    }
    // fragment node
    else if (node.data instanceof UmlSequenceFragment) {
      node.style = { strokeColor: 'cornflowerblue' };
    }
    return node;
  }

  // Export and print logic
  public printDiagram(): void {
    let options: IExportOptions = {};
    options.mode = 'Download';
    options.region = 'Content';
    options.multiplePage = this.diagram.pageSettings.multiplePage;
    options.pageHeight = this.diagram.pageSettings.height;
    options.pageWidth = this.diagram.pageSettings.width;
    this.diagram.print(options);
  }

  // Toolbar actions
  public toolbarClick(args: ClickEventArgs): void {
    let item = args.item.tooltipText;
    switch (item) {
      case 'Select Tool':
        this.diagram.clearSelection();
        this.diagram.tool = DiagramTools.Default;
        break;
      case 'Pan Tool':
        this.diagram.clearSelection();
        this.diagram.tool = DiagramTools.ZoomPan;
        break;
      case 'New Diagram':
        this.diagram.clear();
        break;
      case 'Print Diagram':
        this.printDiagram();
        break;
      case 'Save Diagram':
        this.download(this.diagram.saveDiagram());
        break;
      case 'Open Diagram':
        (document.getElementsByClassName('e-file-select-wrap') as any)[0]
          .querySelector('button')
          .click();
        break;
    }
    this.diagram.dataBind();
  }

  // Zoom change handler
  public zoomChange(args: MenuEventArgs): void {
    const currentZoom = this.diagram.scrollSettings.currentZoom!;
    let zoomFactor: number;

    switch (args.item.text) {
      case 'Zoom In':
        this.diagram.zoomTo({ type: 'ZoomIn', zoomFactor: 0.2 });
        break;
      case 'Zoom Out':
        this.diagram.zoomTo({ type: 'ZoomOut', zoomFactor: 0.2 });
        break;
      case 'Zoom to Fit':
        zoomFactor = 1 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
      case 'Zoom to 50%':
        zoomFactor = 0.5 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
      case 'Zoom to 100%':
        zoomFactor = 1 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
      case 'Zoom to 200%':
        zoomFactor = 2 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
    }

    const zoomCurrentValue: DropDownButtonComponent = (document.getElementById('btnZoomIncrement') as any).ej2_instances[0];
    if (this.diagram.scrollSettings.currentZoom)
      zoomCurrentValue.content = Math.round(this.diagram.scrollSettings.currentZoom * 100) + '%';
  }

  public onselectExport(args: MenuEventArgs): void {
    let exportOptions: IExportOptions = {
      format: args.item.text as FileFormats,
      mode: 'Download',
      region: 'PageSettings',
      fileName: 'Export',
      margin: { left: 0, top: 0, right: 0, bottom: 0 }
    };
    this.diagram.exportDiagram(exportOptions);
  }

  // Handle file upload success
  public onUploadSuccess(args: any): void {
    let reader = new FileReader();
    reader.readAsText(args.file.rawFile);
    reader.onloadend = (event: any) => {
      this.diagram.loadDiagram(event.target.result);
    };
  }

  // Download diagram as JSON
  public download(data: string): void {
    if ((window.navigator as any).msSaveBlob) {
      let blob: Blob = new Blob([data], { type: 'data:text/json;charset=utf-8,' });
      (window.navigator as any).msSaveOrOpenBlob(blob, 'Diagram.json');
    }
    else {
      let dataString = 'data:text/json;charset=utf-8,' + encodeURIComponent(data);
      let element = document.createElement('a');
      element.href = dataString;
      element.download = 'Diagram.json';
      document.body.appendChild(element);
      element.click();
      element.remove();
    }
  }

  // Handle textbox input change
  public onTextBoxChange(args: InputEventArgs) {
    if (args.value !== '') {
      this.sendButton.disabled = false;
    } else {
      this.sendButton.disabled = true;
    }
  }
}
<h4 style="text-align: center;">Text To UML Sequence Diagram</h4>
<div class="description-container e-card">
    <div class='e-card-content'>
        <p>
            This demo illustrates how the Angular Diagram Component, enhanced with AI, generates UML Sequence Diagrams to depict object interactions in a timeline. It offers a dynamic representation of system behaviors showing the sequence of message exchanges.
        </p>
    </div>
</div>
<div class="container">
    <link href="https://ej2.syncfusion.com/javascript/demos/src/diagram/styles/diagram-common.css" rel="stylesheet" />

    <div class="main">
        <div class="diagram-upload-file">
            <ejs-uploader id="fileupload" name="UploadFiles" [asyncSettings]="asyncSettings"
                (success)="onUploadSuccess($event)" [showFileList]="false">
            </ejs-uploader>
        </div>
        <div class="db-toolbar-editor">
            <div class="db-toolbar-container">
                <ejs-toolbar id="toolbarEditor" [width]="'100%'" [height]="49" (clicked)="toolbarClick($event)">
                    <e-items>
                        <e-item prefixIcon="e-icons e-circle-add" tooltipText="New Diagram"></e-item>
                        <e-item prefixIcon="e-icons e-folder-open" tooltipText="Open Diagram"></e-item>
                        <e-item prefixIcon="e-icons e-save" tooltipText="Save Diagram"></e-item>
                        <e-item prefixIcon="e-icons e-print" tooltipText="Print Diagram"></e-item>
                        <e-item type="Input" tooltipText="Export Diagram">
                            <ng-template #template>
                                <button ejs-dropdownbutton id="exportBtn" [items]="exportItems"
                                    [iconCss]="'e-ddb-icons e-export'" (select)="onselectExport($event)">
                                </button>
                            </ng-template>
                        </e-item>
                        <e-item type="Separator"></e-item>
                        <e-item prefixIcon="e-icons e-pan" tooltipText="Pan Tool"
                            cssClass="tb-item-start pan-item"></e-item>
                        <e-item prefixIcon="e-icons e-mouse-pointer" tooltipText="Select Tool"
                            cssClass="tb-item-middle tb-item-selected"></e-item>
                        <e-item type="Separator"></e-item>
                        <e-item cssClass="tb-item-end tb-zoom-dropdown-btn" align="Right">
                            <ng-template #template>
                                <button ejs-dropdownbutton id="btnZoomIncrement" [items]="zoomMenuItems"
                                    [content]="zoomContent" (select)="zoomChange($event)">
                                </button>
                            </ng-template>
                        </e-item>
                    </e-items>
                </ejs-toolbar>
            </div>
        </div>
        <div style="margin-top: 5px;border: 0.5px solid #b0b0b0;">
            <ejs-diagram #diagram id="diagram" width="100%" height="900px"
                [tool]="diagramTools" [snapSettings]="snapSettings" (created)="diagramCreated()"
                [getNodeDefaults]="getNodeDefaults" (scrollChange)="onScrollChange($event)">
            </ejs-diagram>
        </div>
    </div>
    <div id='container'>
        <ejs-dialog #dialog id='dialog' target='#container'
            header='<span class="e-icons e-assistview-icon" style="color: black;width:20px; font-size: 16px;"></span> AI Assist'
            showCloseIcon='true' isModal='true' [visible]='false' [width]="'540px'" [height]="'310px'">
            <p style="margin-bottom: 10px; font-weight: bold;">Suggested Prompts</p>

            <button ejs-button id="btn1" cssClass="e-primary" (click)="onBtnClick('Sequence Diagram for ATM Transaction Process')"
                style="flex: 1; overflow: visible; border-radius: 8px; margin-bottom: 10px">
                Sequence Diagram for ATM Transaction Process
            </button>

            <button ejs-button id="btn2" cssClass="e-primary"
                (click)="onBtnClick('Sequence Diagram for User Authentication and Authorization')"
                style="flex: 1; overflow: visible; border-radius: 8px; margin-bottom: 10px">
                Sequence Diagram for User Authentication and Authorization
            </button>

            <button ejs-button id="btn3" cssClass="e-primary" (click)="onBtnClick('Sequence Diagram for Medical Appointment Scheduling')"
                style="flex: 1; overflow: visible; border-radius: 8px; margin-bottom: 10px">
                Sequence Diagram for Medical Appointment Scheduling
            </button>

            <div style="display: flex; align-items: center; margin-top: 20px;">
                <ejs-textbox #textBox id="textBox" placeholder="Please enter your prompt here..." style="flex: 1;"
                    (input)="onTextBoxChange($event)"></ejs-textbox>

                <button ejs-button id="db-send" (click)="onSendClick()" iconCss='e-icons e-send' cssClass="e-primary"
                    style="margin-left: 5px; height: 32px; width: 32px;"></button>
            </div>
        </ejs-dialog>
    </div>
    <button ejs-fab id="ai-assist" [isPrimary]="true" content="AI Assist" iconCss="e-btn-icon e-icons e-assistview-icon e-icon-left"
        (click)="showDialog()"></button>

    <!-- Loading indicator container -->
    <div id="loadingContainer" class="loading-container">
        <div class="loading-indicator"></div>
        <div class="loading-text">Generating UML Sequence Diagram...</div>
    </div>
</div>

// react/src/ai-components/diagram/smart-umlSequenceDiagram/smart-umlSequenceDiagram.tsx
import {
    DiagramComponent, NodeModel, PrintAndExport, Inject,
    DiagramTools, FileFormats,
    IExportOptions, IScrollChangeEventArgs
} from '@syncfusion/ej2-react-diagrams';
import { UmlSequenceParticipant, UmlSequenceFragment,} from '@syncfusion/ej2-diagrams';
import { ButtonComponent, FabComponent } from '@syncfusion/ej2-react-buttons';
import { convertTextToUmlSequenceDiagram } from './ai-umlSequenceDiagram';
import { sequenceModel, exportItems, zoomMenuItems } from './datasource';
import { ClickEventArgs, ItemDirective, ItemsDirective, ToolbarComponent } from '@syncfusion/ej2-react-navigations';
import { DropDownButtonComponent, MenuEventArgs } from '@syncfusion/ej2-react-splitbuttons';
import { InputEventArgs, TextBoxComponent, UploaderComponent } from '@syncfusion/ej2-react-inputs';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { useEffect } from 'react';
import './smart-umlSequenceDiagram.css';
import { from } from 'form-data';

function SmartUmlSequenceDiagram() {
    let diagram: DiagramComponent;
    let dialog: DialogComponent;
    let msgBtn1: ButtonComponent;
    let msgBtn2: ButtonComponent;
    let msgBtn3: ButtonComponent;
    let textBox: TextBoxComponent;
    let sendButton: ButtonComponent;
    useEffect(() => {
        // Add keypress event listener to the document
        document.addEventListener('keypress', function (event) {
            if (event.key === 'Enter' && document.activeElement === textBox.element) {
                if (textBox.value !== '') {
                    dialog.hide();
                    convertTextToUmlSequenceDiagram(textBox.value, diagram);
                }
            }
        });
    }, []);

    function printDiagram() {
        let options: IExportOptions = {};
        options.mode = 'Download';
        options.region = 'Content';
        options.multiplePage = diagram.pageSettings.multiplePage;
        options.pageHeight = diagram.pageSettings.height;
        options.pageWidth = diagram.pageSettings.width;
        diagram.print(options);
    }
    function toolbarClick(args: ClickEventArgs) {
        let item = args.item.tooltipText;
        switch (item) {
            case 'Select Tool':
                diagram.clearSelection();
                diagram.tool = DiagramTools.Default;
                break;
            case 'Pan Tool':
                diagram.clearSelection();
                diagram.tool = DiagramTools.ZoomPan;
                break;
            case 'New Diagram':
                diagram.clear();
                break;
            case 'Print Diagram':
                printDiagram();
                break;
            case 'Save Diagram':
                download(diagram.saveDiagram());
                break;
            case 'Open Diagram':
                (document.getElementsByClassName('e-file-select-wrap') as any)[0]
                    .querySelector('button')
                    .click();
                break;
        }
        diagram.dataBind();
    }
    function zoomChange(args: MenuEventArgs) {
        const zoomCurrentValue: DropDownButtonComponent = (document.getElementById("btnZoomIncrement") as any).ej2_instances[0];
        const currentZoom: number = diagram.scrollSettings.currentZoom!;
        let zoomFactor: number;
        switch (args.item.text) {
            case 'Zoom In':
                diagram.zoomTo({ type: 'ZoomIn', zoomFactor: 0.2 });
                break;
            case 'Zoom Out':
                diagram.zoomTo({ type: 'ZoomOut', zoomFactor: 0.2 });
                break;
            case 'Zoom to Fit':
                zoomFactor = 1 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
            case 'Zoom to 50%':
                zoomFactor = 0.5 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
            case 'Zoom to 100%':
                zoomFactor = 1 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
            case 'Zoom to 200%':
                zoomFactor = 2 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
        }

        zoomCurrentValue.content = Math.round(diagram.scrollSettings.currentZoom! * 100) + '%';
    }

    //Export the diagraming object based on the format.
    function onselectExport(args: MenuEventArgs) {
        let exportOptions: IExportOptions = {};
        exportOptions.format = args.item.text as FileFormats;
        exportOptions.mode = 'Download';
        exportOptions.region = 'PageSettings';
        exportOptions.fileName = 'Export';
        exportOptions.margin = { left: 0, top: 0, bottom: 0, right: 0 };
        diagram.exportDiagram(exportOptions);
    }
    function onUploadSuccess(args: any) {
        let file = args.file;
        let rawFile = file.rawFile;
        let reader = new FileReader();
        reader.readAsText(rawFile);
        reader.onloadend = loadDiagram;
    }
    function loadDiagram(event: any) {
        diagram.loadDiagram(event.target.result);
    }


    function download(data: string) {
        if ((window.navigator as any).msSaveBlob) {
            let blob: Blob = new Blob([data], { type: 'data:text/json;charset=utf-8,' });
            (window.navigator as any).msSaveOrOpenBlob(blob, 'Diagram.json');
        }
        else {
            let dataString = 'data:text/json;charset=utf-8,' + encodeURIComponent(data);
            let ele = document.createElement('a');
            ele.href = dataString;
            ele.download = 'Diagram.json';
            document.body.appendChild(ele);
            ele.click();
            ele.remove();
        }
    }

    function onTextBoxChange(args: InputEventArgs) {
        if (args.value !== '') {
            sendButton.disabled = false;
        } else {
            sendButton.disabled = true;
        }
    }

    const dialogContent = () => {
        return (
            <>
                <p style={{ marginBottom: '10px', fontWeight: 'bold' }}>Suggested Prompts</p>
                <ButtonComponent ref={(btn1: ButtonComponent) => msgBtn1 = btn1 as ButtonComponent}
                    onClick={() => {
                        dialog.hide();
                        convertTextToUmlSequenceDiagram((msgBtn1 as any).value, diagram);
                    }}
                    id="btn1" style={{ flex: 1, overflow: 'visible', borderRadius: '8px', marginBottom: '10px' }}
                >Sequence Diagram for ATM Transaction Process</ButtonComponent>

                <ButtonComponent
                    ref={(btn2: ButtonComponent) => msgBtn2 = btn2 as ButtonComponent}
                    id="btn2" style={{ flex: 1, overflow: 'visible', borderRadius: '8px', marginBottom: '10px' }}
                    onClick={() => {
                        dialog.hide();
                        convertTextToUmlSequenceDiagram((msgBtn2 as any).value, diagram);
                    }}
                >Sequence Diagram for User Authentication and Authorization</ButtonComponent>
                
                <ButtonComponent
                    ref={(btn3: ButtonComponent) => msgBtn3 = btn3 as ButtonComponent}
                    onClick={() => {
                        dialog.hide();
                        convertTextToUmlSequenceDiagram((msgBtn3 as any).value, diagram);
                    }}
                    id="btn3" style={{ flex: 1, overflow: 'visible', borderRadius: '8px', marginBottom: '10px' }}
                >Sequence Diagram for Medical Appointment Scheduling</ButtonComponent>
                
                <div style={{ display: 'flex', alignItems: 'center', marginTop: '20px' }}>
                    <TextBoxComponent type="text" id="textBox" className="db-openai-textbox" style={{ flex: 1 }}
                        ref={(textboxObj: TextBoxComponent) => textBox = textboxObj as TextBoxComponent}
                        placeholder='Please enter your prompt here...' width={450} input={onTextBoxChange}
                    />
                    <ButtonComponent id="db-send"
                        ref={(btn: ButtonComponent) => sendButton = btn as ButtonComponent}
                        onClick={() => {
                            dialog.hide();
                            convertTextToUmlSequenceDiagram(textBox.value, diagram)
                        }}
                        iconCss='e-icons e-send' isPrimary={true} disabled={true}
                        style={{ marginLeft: '5px', height: '32px', width: '32px' }}></ButtonComponent>
                </div>
            </>
        );
    }

    return (
        <>
            <div className="description-container e-card">
                <div className='e-card-content'>
                    <p>
                        This demo illustrates how the JavaScript Diagram Component, enhanced with AI, generates UML Sequence Diagrams representing object interactions in a time sequence. It visually depicts object collaborations and message exchanges, providing a clear and interactive means to model dynamic behaviors in systems.
                        Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/diagram/Readme.md">here</a>.
                    </p>
                </div>
            </div>
            <div className="container">
                <link href="https://ej2.syncfusion.com/javascript/demos/src/diagram/styles/diagram-common.css" rel="stylesheet" />
                <div className="main">
                    <div className="diagram-upload-file">
                        <UploaderComponent
                            type="file"
                            id="fileupload"
                            name="UploadFiles"
                            asyncSettings={{
                                saveUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Save',
                                removeUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Remove'
                            }}
                            success={onUploadSuccess}
                            showFileList={false}
                        />
                    </div>
                    <div className="db-toolbar-editor">
                        <div className="db-toolbar-container">
                            <ToolbarComponent id="toolbarEditor"
                                clicked={toolbarClick}
                                width='100%' height={49}
                            >
                                <ItemsDirective>
                                    <ItemDirective prefixIcon='e-icons e-circle-add' tooltipText='New Diagram' />
                                    <ItemDirective prefixIcon='e-icons e-folder-open' tooltipText='Open Diagram' />
                                    <ItemDirective prefixIcon='e-icons e-save' tooltipText='Save Diagram' />
                                    <ItemDirective prefixIcon='e-print e-icons' tooltipText='Print Diagram' />
                                    <ItemDirective type='Input' tooltipText='Export Diagram'
                                        template={() => <DropDownButtonComponent id="exportBtn" style={{ width: '100%' }}
                                            items={exportItems} iconCss='e-ddb-icons e-export' select={function (args: any) { onselectExport(args); }}
                                        ></DropDownButtonComponent>}
                                    />
                                    <ItemDirective type='Separator' />
                                    <ItemDirective prefixIcon='e-pan e-icons' tooltipText='Pan Tool' cssClass='tb-item-start pan-item' />
                                    <ItemDirective prefixIcon='e-mouse-pointer e-icons' tooltipText='Select Tool' cssClass='tb-item-middle tb-item-selected' />
                                    <ItemDirective type='Separator' />
                                    <ItemDirective cssClass='tb-item-end tb-zoom-dropdown-btn' align='Right'
                                        template={() => <DropDownButtonComponent id="btnZoomIncrement"
                                            items={zoomMenuItems} content={Math.round(diagram.scrollSettings.currentZoom! * 100) + ' %'} select={zoomChange}
                                        ></DropDownButtonComponent>}
                                    />
                                </ItemsDirective>
                            </ToolbarComponent>
                        </div>
                    </div>
                    <div style={{ marginTop: '5px', marginLeft: '5px', marginRight: '5px', border: '1px solid #b0b0b0' }}>
                        <DiagramComponent
                            ref={(diagramObj: DiagramComponent) => diagram = diagramObj as DiagramComponent}
                            id="diagram"
                            width="100%"
                            height="900px"
                            tool={DiagramTools.ZoomPan}
                            model={sequenceModel}
                            getNodeDefaults={(node: NodeModel) => {
                                // participant node
                                if (node.data instanceof UmlSequenceParticipant) {
                                    if (!((node.data as any).isActor)) {
                                        if (node.annotations && node.annotations[0] && node.annotations[0].style) {
                                            node.annotations[0].style.color = 'white';
                                        }
                                    }
                                }    // fragment node
                                else if (node.data instanceof UmlSequenceFragment) {
                                    node.style = { strokeColor: 'cornflowerblue' };
                                }
                            }}
                            scrollChange={(args: IScrollChangeEventArgs) => {
                                if (args.panState !== 'Start') {
                                    let zoomCurrentValue: any = (document.getElementById("btnZoomIncrement") as any).ej2_instances[0];
                                    zoomCurrentValue.content = Math.round(diagram.scrollSettings.currentZoom! * 100) + ' %';
                                }
                            }}
                        >
                            <Inject services={[PrintAndExport]} />
                        </DiagramComponent>
                    </div>
                </div>
                <div id='dialog-container'>
                    <DialogComponent
                        ref={(dialogObj: DialogComponent) => dialog = dialogObj as DialogComponent}
                        id='dialog'
                        header='<span class="e-icons e-assistview-icon" style="color: black;width:20px; font-size: 16px;"></span> AI Assist'
                        showCloseIcon={true}
                        isModal={true}
                        content={dialogContent}
                        target={document.getElementById('control-section') as HTMLElement}
                        width='540px'
                        visible={false}
                        height='310px'
                    />
                </div>
                <FabComponent id="ai-assist"
                    isPrimary={true} content='AI Assist' iconCss='e-icons e-assistview-icon'
                    onClick={() => { dialog.show(); }}
                ></FabComponent>

                {/* Loading indicator container */}
                <div id="loadingContainer" className="loading-container">
                    <div className="loading-indicator"></div>
                    <div className="loading-text">Generating Sequence Diagram...</div>
                </div>
            </div >
        </>
    )
}

export default SmartUmlSequenceDiagram
