// angular/src/app/maps/weather-prediction/weather-prediction.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { ButtonAllModule,Button } from '@syncfusion/ej2-angular-buttons';
import { MapsAllModule } from '@syncfusion/ej2-angular-maps';

import { getAzureChatAIRequest } from '../../ai-models/ai-models';
interface MarkerData {
  latitude: number;
  longitude: number;
  name: string;
  temperature: number;
  weatherCondition: string;
}

@Component({
  selector: 'app-weather-prediction',
  standalone: true,
  imports: [ButtonAllModule, MapsAllModule],
  templateUrl: './weather-prediction.component.html',
  styleUrl: './weather-prediction.component.css'
})

export class WeatherPredictionComponent {
  @ViewChild('maps', { static: false }) map!: ElementRef;
  @ViewChild('tomorrowButton', { static: false }) tomorrowButton!: ElementRef;
  @ViewChild('secondDayButton', { static: false }) secondDayButtonInstance!: ElementRef;
  @ViewChild('thirdDayButton', { static: false }) thirdDayButtonInstance!: ElementRef;
  @ViewChild('fourthDayButton', { static: false }) fourthDayButtonInstance!: ElementRef;
  @ViewChild('fifthDayButton', { static: false }) fifthDayButtonInstance!: ElementRef;
  public height:string="630px";
  public todayDate: Date = new Date();
  public tomorrow:string="Tomorrow"
  public secondDay:string="Second Day";
  public thirdDay:string="Third Day";
  public fourth:string="Fourth Day";
  public fifthDay:string="Fifth Day";
  public secondDayDate: Date = this.addDays(this.todayDate, 2);
  public thirdDayDate: Date = this.addDays(this.todayDate, 3);
  public fourthDayDate: Date = this.addDays(this.todayDate, 4);
  public fifthDayDate: Date = this.addDays(this.todayDate, 5);
  public markerDataSource: MarkerData[] = [];
  public secondDayText: string = this.secondDayDate.toLocaleDateString('en-US', { weekday: 'long' });
  public thirdDayText: string = this.thirdDayDate.toLocaleDateString('en-US', { weekday: 'long' });
  public fourthDayText: string = this.fourthDayDate.toLocaleDateString('en-US', { weekday: 'long' });
  public fifthDayText: string = this.fifthDayDate.toLocaleDateString('en-US', { weekday: 'long' });
  public centerPosition?:object;
  public margin?:object;
  public zoomSettings?:object;
  public tooltipSettings?:object;
  public urlTemplate?:string;
  public markerSettings?:any;
  public annotations?: { content: string; x: string; y: string; zIndex:string}[];
  ngOnInit() {
    this.centerPosition= {
      latitude: 35.07653392014242,
      longitude: -95.40586193773237
  }
  this.margin= {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0
}
this.zoomSettings= {
  enable: false,
  maxZoom: 19,
  zoomFactor: 5,
  toolbarSettings: {
      buttonSettings: {
          toolbarItems: ['Zoom', 'ZoomIn', 'ZoomOut', 'Pan', 'Reset'],
      }
  }
}
this.annotations= [
  {
      content: '<div style="display: flex">' +
          '<div style="background-color: dodgerblue; color:white; font-size: 16px; padding:5px 10px 5px; width: max-content;">Weather Forecast</div>' +
          '<div style="background-color: white; color:black; font-size: 16px; padding:5px 10px 5px">Today</div>' +
          '</div>',
      x: '80%',
      y: '0%',
      zIndex: '1'
  }
]
this.urlTemplate='https://a.tile.openstreetmap.org/level/tileX/tileY.png';
this.tooltipSettings= {
  visible: true,
  valuePath: 'name'
}
this.markerSettings= [{
  visible: true,
  template: '<div style="display:flex; transform:translate(-50%, -50%)">' +
      '<div style="background-color:black; opacity:0.8; align-content:center; padding-left:5px;padding-right:5px">' +
      '<img class="markerTemplate" src="${weatherImage}" alt="Weather" height="35px" width="35px" />' +
      '</div>' +
      '<div style="background-color:#fff; opacity:0.8; padding-left:5px;padding-right:5px">' +
      '<span style="font-size:12px;font-weight:bold">${city_name}</span><br />' +
      '<span style="font-size:16px;font-weight:bold">${temperature} °C</span>' +
      '</div>' +
      '</div>',
  dataSource: this.markerDataSource,
  animationDuration: 0,
}]
  }

  private addDays(date: Date, days: number): Date {
    const result = new Date(date);
    result.setDate(date.getDate() + days);
    return result;
  }

  public getWeatherData(day: string): void {
    let weatherDataRequest;
    let offset: number = 0;
    let buttonInstance: Button;
    if ((day === 'Tomorrow') || (day === 'Second Day') || (day === 'Third Day') || (day === 'Fourth Day') || (day === 'Fifth Day')) {
        if (day === 'Tomorrow') {
            offset = 1;
            buttonInstance = this.tomorrowButton as any;
        } else if (day === 'Second Day') {
            offset = 2;
            buttonInstance = this.secondDayButtonInstance as any;
        } else if (day === 'Third Day') {
            offset = 3;
            buttonInstance = this.thirdDayButtonInstance as any;
        } else if (day === 'Fourth Day') {
            offset = 4;
            buttonInstance = this.fourthDayButtonInstance as any;
        } else if (day === 'Fifth Day') {
            offset = 5;
            buttonInstance = this.fifthDayButtonInstance as any;
        }
        const dateTime = new Date();
        dateTime.setDate(dateTime.getDate() + offset);
        const dayValue = dateTime.getDate().toString();
        const month = (dateTime.getMonth() + 1).toString();
        const year = dateTime.getFullYear().toString();
        const date = `${dayValue}/${month}/${year}`;
        weatherDataRequest = this.generateWeatherRequest(date);
    } else {
        weatherDataRequest = this.generateWeatherRequest('today');
    }
    weatherDataRequest.then((data:any) => {
        if (data) {
            if (data.indexOf('```json') > -1) {
                let cleanedResponseText = data.split('```json')[1].trim();
                data = cleanedResponseText.split("```")[0].trim();
            }
            data = JSON.parse(data);
            this.markerDataSource = data.map((marker: any) => ({
                ...marker,
                weatherImage: this.getWeatherImage(marker.weather_condition)
            }));
            (this.map as any).layers[0].markerSettings[0].dataSource = this.markerDataSource;
            if (buttonInstance) {
                (this.map as any).annotations[0].content = '<div style="display: flex">' +
                    '<div style="background-color: dodgerblue; color:white; font-size: 16px; padding:5px 10px 5px; width: max-content;">Weather Forecast</div>' +
                    '<div style="background-color: white; color:black; font-size: 16px; padding:5px 10px 5px">' + buttonInstance.content + '</div>' +
                    '</div>';
            }
        }
    });
}

public generateWeatherRequest(date: string): Promise<any> {
  const prompt = 'Generate ' + date + '\'s temperature in Celsius for 15 important cities in USA as a JSON object, with fields such as "city_name", "temperature", "latitude", "longitude" and "weather_condition". The weather conditions must be sunny day, rainy day, cloudy day, snowy day and foggy day based on the temperature of the state. Strictly provide flat JSON object list alone without nested objects.';
  return getAzureChatAIRequest({ messages: [{ role: 'user', content: prompt }] });
}

public getWeatherImage(condition: string): string {
  switch (condition.toLowerCase()) {
      case 'sunny day': return 'https://ej2.syncfusion.com/demos/src/maps/images/weather-clear.png';
      case 'snowy day': return 'weather-snow.svg';
      case 'foggy day': return 'weather-foggy.svg';
      case 'cloudy day': return 'https://ej2.syncfusion.com/demos/src/maps/images/weather-clouds.png';
      case 'rainy day': return 'https://ej2.syncfusion.com/demos/src/maps/images/weather-rain.png';
      default: return 'weather-unknown';
  }
}

public onMapsLoaded(): void {
  if (this.markerDataSource.length === 0) {
      this.getWeatherData('Today');
  }
}
}

<h2 style="text-align: center;">Smart Weather Prediction</h2>
    <div class="description-container e-card">
        <div class='e-card-content '>
            <!--!-->
            <p>
                This sample demonstrates the integration of AI to automatically forecast weather conditions in the United States for the next five days, utilizing marker templates within the Map control.
            </p>
        </div>
    </div>
    <ejs-maps #maps id='container' style="display:block;" [height]="height" [annotations]="annotations" [zoomSettings]="zoomSettings" [margin]="margin"
    [centerPosition]="centerPosition" (loaded)="onMapsLoaded()">
        <e-layers>
        <e-layer [urlTemplate]="urlTemplate" [tooltipSettings]="tooltipSettings" [markerSettings]="markerSettings"></e-layer>
        </e-layers>
        </ejs-maps>
    <div  style="display:flex; justify-content: center; align-items: center;">
        <button #tomorrowButton ejs-button style="margin: 5px;" (click)="getWeatherData(tomorrow)">Tomorrow</button>
        <button #secondDayButton ejs-button style="margin: 5px;" (click)="getWeatherData(secondDay)">{{secondDayText}}</button>
        <button #thirdDayButton ejs-button style="margin: 5px;" (click)="getWeatherData(thirdDay)">{{thirdDayText}}</button>
        <button #fourthDay ejs-button style="margin: 5px;" (click)="getWeatherData(fourth)">{{fourthDayText}}</button>
        <button #fifthDayButton ejs-button style="margin: 5px;" (click)="getWeatherData(fifthDay)">{{fifthDayText}}</button>
    </div>

// react/src/ai-components/maps/weather-prediction.tsx
import { LayerDirective, LayersDirective, MapsComponent, Marker, MapsTooltip, Annotations, Zoom, Inject, AnnotationsDirective, AnnotationDirective } from '@syncfusion/ej2-react-maps';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { getAzureChatAIRequest } from '../../ai-models';

function WeatherPrediction() {
    let mapInstance: MapsComponent;
    let markerDataSource: MarkerData[] = [];
    interface MarkerData {
        latitude: number;
        longitude: number;
        name: string;
        temperature: number;
        weatherCondition: string;
    };
    let tomorrowButton: ButtonComponent;
    let secondDayButtonInstance: ButtonComponent;
    let thirdDayButtonInstance: ButtonComponent;
    let fourthDayButtonInstance: ButtonComponent;
    let fifthDayButtonInstance: ButtonComponent;

    const todayDate = new Date();
    const secondDayDate = new Date(todayDate);
    secondDayDate.setDate(todayDate.getDate() + 2);
    const thirdDayDate = new Date(todayDate);
    thirdDayDate.setDate(todayDate.getDate() + 3);
    const fourthDayDate = new Date(todayDate);
    fourthDayDate.setDate(todayDate.getDate() + 4);
    const fifthDayDate = new Date(todayDate);
    fifthDayDate.setDate(todayDate.getDate() + 5);

    const secondDayText = (secondDayDate).toLocaleDateString('en-US', { weekday: 'long' });
    const thirdDayText = thirdDayDate.toLocaleDateString('en-US', { weekday: 'long' });
    const fourthDayText = fourthDayDate.toLocaleDateString('en-US', { weekday: 'long' });
    const fifthDayText = fifthDayDate.toLocaleDateString('en-US', { weekday: 'long' });

    function onMapsLoaded(): void {
        if (markerDataSource.length === 0) {
            getWeatherData('Today');
        }
    }

    function getWeatherData(day: string): void {
        let weatherDataRequest;
        let offset: number = 0;
        let buttonInstance: ButtonComponent;
        if ((day === 'Tomorrow') || (day === 'Second Day') || (day === 'Third Day') || (day === 'Fourth Day') || (day === 'Fifth Day')) {
            if (day === 'Tomorrow') {
                offset = 1;
                buttonInstance = tomorrowButton;
            } else if (day === 'Second Day') {
                offset = 2;
                buttonInstance = secondDayButtonInstance;
            } else if (day === 'Third Day') {
                offset = 3;
                buttonInstance = thirdDayButtonInstance;
            } else if (day === 'Fourth Day') {
                offset = 4;
                buttonInstance = fourthDayButtonInstance;
            } else if (day === 'Fifth Day') {
                offset = 5;
                buttonInstance = fifthDayButtonInstance;
            }
            const dateTime = new Date();
            dateTime.setDate(dateTime.getDate() + offset);
            const dayValue = dateTime.getDate().toString();
            const month = (dateTime.getMonth() + 1).toString();
            const year = dateTime.getFullYear().toString();
            const date = `${dayValue}/${month}/${year}`;
            weatherDataRequest = generateWeatherRequest(date);
        } else {
            weatherDataRequest = generateWeatherRequest('today');
        }
        weatherDataRequest.then((data) => {
            if (data) {
                if (data.indexOf('```json') > -1) {
                    let cleanedResponseText = data.split('```json')[1].trim();
                    data = cleanedResponseText.split("```")[0].trim();
                }
                data = JSON.parse(data);
                markerDataSource = data.map((marker: any) => ({
                    ...marker,
                    weatherImage: getWeatherImage(marker.weather_condition)
                }));
                (mapInstance as any).layers[0].markerSettings[0].dataSource = markerDataSource;
                if (buttonInstance) {
                    (mapInstance as any).annotations[0].content = '<div style="display: flex">' +
                        '<div style="background-color: dodgerblue; color:white; font-size: 16px; padding:5px 10px 5px; width: max-content;">Weather Forecast</div>' +
                        '<div style="background-color: white; color:black; font-size: 16px; padding:5px 10px 5px">' + buttonInstance.content + '</div>' +
                        '</div>';
                }
            }
        });
    }

    function generateWeatherRequest(date: string): Promise<any> {
        const prompt = 'Generate ' + date + '\'s temperature in Celsius for 15 important cities in USA as a JSON object, with fields such as "city_name", "temperature", "latitude", "longitude" and "weather_condition". The weather conditions must be sunny day, rainy day, cloudy day, snowy day and foggy day based on the temperature of the state. Strictly provide flat JSON object list alone without nested objects.';
        return getAzureChatAIRequest({ messages: [{ role: 'user', content: prompt }] });
    }

    function getWeatherImage(condition: string): string {
        switch (condition.toLowerCase()) {
            case 'sunny day': return 'https://ej2.syncfusion.com/demos/src/maps/images/weather-clear.png';
            case 'snowy day': return 'weather-snow.svg';
            case 'foggy day': return 'weather-foggy.svg';
            case 'cloudy day': return 'https://ej2.syncfusion.com/demos/src/maps/images/weather-clouds.png';
            case 'rainy day': return 'https://ej2.syncfusion.com/demos/src/maps/images/weather-rain.png';
            default: return 'weather-unknown';
        }
    }

    return (
        <div className='control-pane'>
            <div className='control-section'>
                <div className="description-container e-card">
                    <div className='e-card-content'>
                        <p>Syncfusion React Maps integrated with AI to automatically forecast weather conditions in the United States for the next five days. Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/maps/Readme.md">here</a>.</p>
                    </div>
                </div>
                <div id='container'>
                    <MapsComponent
                        ref={map => mapInstance = map as MapsComponent}
                        id='Maps'
                        height='630px'
                        centerPosition={{
                            latitude: 35.07653392014242,
                            longitude: -95.40586193773237
                        }}
                        margin={{
                            top: 0,
                            bottom: 0,
                            left: 0,
                            right: 0
                        }}
                        zoomSettings={{
                            enable: false,
                            maxZoom: 19,
                            zoomFactor: 5,
                            toolbarSettings: {
                                buttonSettings: {
                                    toolbarItems: ['Zoom', 'ZoomIn', 'ZoomOut', 'Pan', 'Reset'],
                                }
                            }
                        }}
                        annotations={[
                            {
                                content: '<div style="display: flex">' +
                                    '<div style="background-color: dodgerblue; color:white; font-size: 16px; padding:5px 10px 5px; width: max-content;">Weather Forecast</div>' +
                                    '<div style="background-color: white; color:black; font-size: 16px; padding:5px 10px 5px">Today</div>' +
                                    '</div>',
                                x: '80%',
                                y: '0%',
                                zIndex: '1'
                            }
                        ]}
                        loaded={onMapsLoaded}
                    >
                        <LayersDirective>
                            <LayerDirective
                                urlTemplate='https://a.tile.openstreetmap.org/level/tileX/tileY.png'
                                tooltipSettings={{
                                    visible: true,
                                    valuePath: 'name'
                                }}
                                markerSettings={[{
                                    visible: true,
                                    template: '<div style="display:flex; transform:translate(-50%, -50%)">' +
                                        '<div style="background-color:black; opacity:0.8; align-content:center; padding-left:5px;padding-right:5px">' +
                                        '<img class="markerTemplate" src="${weatherImage}" alt="Weather" height="35px" width="35px" />' +
                                        '</div>' +
                                        '<div style="background-color:#fff; opacity:0.8; padding-left:5px;padding-right:5px">' +
                                        '<span style="font-size:12px;font-weight:bold">${city_name}</span><br />' +
                                        '<span style="font-size:16px;font-weight:bold">${temperature} °C</span>' +
                                        '</div>' +
                                        '</div>',
                                    dataSource: markerDataSource,
                                    animationDuration: 0,
                                }]}
                            >
                            </LayerDirective>
                        </LayersDirective>
                        <AnnotationsDirective>
                            <AnnotationDirective x='80%' y='0%' zIndex='1'
                                content={'<div style="display: flex">' +
                                    '<div style="background-color: dodgerblue; color:white; font-size: 16px; padding:5px 10px 5px; width: max-content;">Weather Forecast</div>' +
                                    '<div style="background-color: white; color:black; font-size: 16px; padding:5px 10px 5px">Today</div>' +
                                    '</div>'}
                            ></AnnotationDirective>
                        </AnnotationsDirective>
                        <Inject services={[Marker, MapsTooltip, Zoom, Annotations]} />
                    </MapsComponent>
                    <br></br>
                    <div style={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
                        <ButtonComponent style={{ margin: "5px" }} id="tomorrowButton" onClick={() => getWeatherData('Tomorrow')} content='Tomorrow'></ButtonComponent>
                        <ButtonComponent style={{ margin: "5px" }} id="secondDayButton" onClick={() => getWeatherData('Second Day')} content={secondDayText}></ButtonComponent>
                        <ButtonComponent style={{ margin: "5px" }} id="thirdDayButton" onClick={() => getWeatherData('Third Day')} content={thirdDayText}></ButtonComponent>
                        <ButtonComponent style={{ margin: "5px" }} id="fourthDayButton" onClick={() => getWeatherData('Fourth Day')} content={fourthDayText}></ButtonComponent>
                        <ButtonComponent style={{ margin: "5px" }} id="fifthDayButton" onClick={() => getWeatherData('Fifth Day')} content={fifthDayText}></ButtonComponent>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default WeatherPrediction
