// react/src/ai-components/diagram/smart-flowchart/smart-flowchart.tsx
import {
    DiagramComponent, NodeModel, ConnectorModel,
    SymbolInfo, IDragEnterEventArgs, GridlinesModel, PaletteModel, Node,
    DataBinding, PrintAndExport, FlowchartLayout, Inject,
    SymbolPaletteComponent
} from '@syncfusion/ej2-react-diagrams';
import {
    Connector, DiagramTools, FileFormats, FlowShapeModel,
    IExportOptions, IScrollChangeEventArgs, PathAnnotationModel
} from '@syncfusion/ej2-react-diagrams';
import { ButtonComponent, FabComponent } from '@syncfusion/ej2-react-buttons';
import { DataManager } from "@syncfusion/ej2-data";
import { convertTextToFlowchart } from './ai-flowchart';
import { flowchartData, flowShapes, exportItems, zoomMenuItems, connectorSymbols } from './datasource';
import { ClickEventArgs, ItemDirective, ItemsDirective, ToolbarComponent } from '@syncfusion/ej2-react-navigations';
import { DropDownButtonComponent, MenuEventArgs } from '@syncfusion/ej2-react-splitbuttons';
import { InputEventArgs, TextBoxComponent, UploaderComponent } from '@syncfusion/ej2-react-inputs';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { useEffect } from 'react';
import './smart-flowchart.css';

function SmartFlowchart() {
    let diagram: DiagramComponent;
    let dialog: DialogComponent;
    let msgBtn1: ButtonComponent;
    let msgBtn2: ButtonComponent;
    let msgBtn3: ButtonComponent;
    let textBox: TextBoxComponent;
    let sendButton: ButtonComponent;
    useEffect(() => {
        // Add keypress event listener to the document
        document.addEventListener('keypress', function (event) {
            if (event.key === 'Enter' && document.activeElement === textBox.element) {
                if (textBox.value !== '') {
                    dialog.hide();
                    convertTextToFlowchart(textBox.value, diagram);
                }
            }
        });
    }, []);
    //Sets the Node style for DragEnter element.
    function dragEnter(args: IDragEnterEventArgs): void {
        let obj: NodeModel = args.element as NodeModel;
        if (obj instanceof Node) {
            let oWidth: number = obj.width;
            let oHeight: number = obj.height;
            let ratio: number = 100 / obj.width;
            obj.width = 100;
            obj.height *= ratio;
            obj.offsetX += (obj.width - oWidth) / 2;
            obj.offsetY += (obj.height - oHeight) / 2;
            obj.style = { fill: '#357BD2', strokeColor: 'white' };
        }
    }

    function getSymbolDefaults(symbol: NodeModel): void {
        symbol.style = { strokeColor: '#757575' };
        const wideSymbols = new Set(['Terminator', 'Process', 'Delay']);
        const mediumSymbols = new Set(['Decision', 'Document', 'PreDefinedProcess', 'PaperTap', 'DirectData', 'MultiDocument', 'Data']);
        if (wideSymbols.has((symbol as Node).id)) {
            symbol.width = 80;
            symbol.height = 40;
        } else if (mediumSymbols.has((symbol as Node).id)) {
            symbol.width = 50;
            symbol.height = 40;
        } else {
            symbol.width = 50;
            symbol.height = 50;
        }
    }

    function getSymbolInfo(): SymbolInfo {
        return { fit: true };
    }
    let interval: number[] = [
        1, 9, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75
    ];

    let gridlines: GridlinesModel = { lineColor: '#e0e0e0', lineIntervals: interval };

    function printDiagram() {
        let options: IExportOptions = {};
        options.mode = 'Download';
        options.region = 'Content';
        options.multiplePage = diagram.pageSettings.multiplePage;
        options.pageHeight = diagram.pageSettings.height;
        options.pageWidth = diagram.pageSettings.width;
        diagram.print(options);
    }
    function toolbarClick(args: ClickEventArgs) {
        let item = args.item.tooltipText;
        switch (item) {
            case 'Select Tool':
                diagram.clearSelection();
                diagram.tool = DiagramTools.Default;
                break;
            case 'Pan Tool':
                diagram.clearSelection();
                diagram.tool = DiagramTools.ZoomPan;
                break;
            case 'New Diagram':
                diagram.clear();
                break;
            case 'Print Diagram':
                printDiagram();
                break;
            case 'Save Diagram':
                download(diagram.saveDiagram());
                break;
            case 'Open Diagram':
                (document.getElementsByClassName('e-file-select-wrap') as any)[0]
                    .querySelector('button')
                    .click();
                break;
        }
        diagram.dataBind();
    }
    function zoomChange(args: MenuEventArgs) {
        const zoomCurrentValue: DropDownButtonComponent = (document.getElementById("btnZoomIncrement") as any).ej2_instances[0];
        const currentZoom: number = diagram.scrollSettings.currentZoom!;
        let zoomFactor: number;
        switch (args.item.text) {
            case 'Zoom In':
                diagram.zoomTo({ type: 'ZoomIn', zoomFactor: 0.2 });
                break;
            case 'Zoom Out':
                diagram.zoomTo({ type: 'ZoomOut', zoomFactor: 0.2 });
                break;
            case 'Zoom to Fit':
                zoomFactor = 1 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
            case 'Zoom to 50%':
                zoomFactor = 0.5 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
            case 'Zoom to 100%':
                zoomFactor = 1 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
            case 'Zoom to 200%':
                zoomFactor = 2 / currentZoom - 1;
                diagram.zoomTo({ zoomFactor });
                break;
        }

        zoomCurrentValue.content = Math.round(diagram.scrollSettings.currentZoom! * 100) + '%';
    }

    //Export the diagraming object based on the format.
    function onselectExport(args: MenuEventArgs) {
        let exportOptions: IExportOptions = {};
        exportOptions.format = args.item.text as FileFormats;
        exportOptions.mode = 'Download';
        exportOptions.region = 'PageSettings';
        exportOptions.fileName = 'Export';
        exportOptions.margin = { left: 0, top: 0, bottom: 0, right: 0 };
        diagram.exportDiagram(exportOptions);
    }
    function onUploadSuccess(args: any) {
        let file = args.file;
        let rawFile = file.rawFile;
        let reader = new FileReader();
        reader.readAsText(rawFile);
        reader.onloadend = loadDiagram;
    }
    function loadDiagram(event: any) {
        diagram.loadDiagram(event.target.result);
    }


    function download(data: string) {
        if ((window.navigator as any).msSaveBlob) {
            let blob: Blob = new Blob([data], { type: 'data:text/json;charset=utf-8,' });
            (window.navigator as any).msSaveOrOpenBlob(blob, 'Diagram.json');
        }
        else {
            let dataString = 'data:text/json;charset=utf-8,' + encodeURIComponent(data);
            let ele = document.createElement('a');
            ele.href = dataString;
            ele.download = 'Diagram.json';
            document.body.appendChild(ele);
            ele.click();
            ele.remove();
        }
    }

    let palettes: PaletteModel[] = [
        { id: 'flow', expanded: true, symbols: flowShapes, iconCss: 'e-ddb-icons e-flow', title: 'Flow Shapes' },
        { id: 'connectors', expanded: true, symbols: connectorSymbols, iconCss: 'e-ddb-icons e-connector', title: 'Connectors' }
    ];

    function onTextBoxChange(args: InputEventArgs) {
        if (args.value !== '') {
            sendButton.disabled = false;
        } else {
            sendButton.disabled = true;
        }
    }

    const dialogContent = () => {
        return (
            <>
                <p style={{ marginBottom: '10px', fontWeight: 'bold' }}>Suggested Prompts</p>
                <ButtonComponent
                    ref={btn2 => msgBtn2 = btn2 as ButtonComponent}
                    id="btn2" style={{ flex: 1, overflow: 'visible', borderRadius: '8px', marginBottom: '10px' }}
                    onClick={() => {
                        dialog.hide();
                        convertTextToFlowchart((msgBtn2 as any).value, diagram);
                    }}
                >Flowchart for online shopping</ButtonComponent>
                <ButtonComponent ref={btn1 => msgBtn1 = btn1 as ButtonComponent}
                    onClick={() => {
                        dialog.hide();
                        convertTextToFlowchart((msgBtn1 as any).value, diagram);
                    }}
                    id="btn1" style={{ flex: 1, overflow: 'visible', borderRadius: '8px', marginBottom: '10px' }}>Flowchart for Mobile banking registration</ButtonComponent>
                <ButtonComponent
                    ref={btn3 => msgBtn3 = btn3 as ButtonComponent}
                    onClick={() => {
                        dialog.hide();
                        convertTextToFlowchart((msgBtn3 as any).value, diagram);
                    }}
                    id="btn3" style={{ flex: 1, overflow: 'visible', borderRadius: '8px', marginBottom: '10px' }}>Flowchart for Bus ticket booking</ButtonComponent>
                <div style={{ display: 'flex', alignItems: 'center', marginTop: '20px' }}>
                    <TextBoxComponent type="text" id="textBox" className="db-openai-textbox" style={{ flex: 1 }}
                        ref={textboxObj => textBox = textboxObj as TextBoxComponent}
                        placeholder='Please enter your prompt here...' width={450} input={onTextBoxChange}
                    />
                    <ButtonComponent id="db-send"
                        ref={btn => sendButton = btn as ButtonComponent}
                        onClick={() => {
                            dialog.hide();
                            convertTextToFlowchart(textBox.value, diagram)
                        }}
                        iconCss='e-icons e-send' isPrimary={true} disabled={true}
                        style={{ marginLeft: '5px', height: '32px', width: '32px' }}></ButtonComponent>
                </div>
            </>
        );
    }

    return (
        <>
            <div className="description-container e-card">
                <div className='e-card-content'>
                    <p>
                        This demo demonstrates how the React Diagram Component, enhanced with AI, creates flowcharts using nodes and connectors. It visually represents processes, workflows, and decision paths, providing a clear and interactive way to map out procedures.
                        Know more <a href="https://github.com/syncfusion/smart-ai-samples/blob/master/react/src/ai-components/diagram/Readme.md">here</a>.
                    </p>
                </div>
            </div>
            <div className="container">
                <link href="https://ej2.syncfusion.com/javascript/demos/src/diagram/styles/diagram-common.css" rel="stylesheet" />
                <div className="main">
                    <div className="diagram-upload-file">
                        <UploaderComponent
                            type="file"
                            id="fileupload"
                            name="UploadFiles"
                            asyncSettings={{
                                saveUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Save',
                                removeUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Remove'
                            }}
                            success={onUploadSuccess}
                            showFileList={false}
                        />
                    </div>
                    <div className="db-toolbar-editor">
                        <div className="db-toolbar-container">
                            <ToolbarComponent id="toolbarEditor"
                                clicked={toolbarClick}
                                width='100%' height={49}
                            >
                                <ItemsDirective>
                                    <ItemDirective prefixIcon='e-icons e-circle-add' tooltipText='New Diagram' />
                                    <ItemDirective prefixIcon='e-icons e-folder-open' tooltipText='Open Diagram' />
                                    <ItemDirective prefixIcon='e-icons e-save' tooltipText='Save Diagram' />
                                    <ItemDirective prefixIcon='e-print e-icons' tooltipText='Print Diagram' />
                                    <ItemDirective type='Input' tooltipText='Export Diagram'
                                        template={() => <DropDownButtonComponent id="exportBtn" style={{ width: '100%' }}
                                            items={exportItems} iconCss='e-ddb-icons e-export' select={function (args: any) { onselectExport(args); }}
                                        ></DropDownButtonComponent>}
                                    />
                                    <ItemDirective type='Separator' />
                                    <ItemDirective prefixIcon='e-pan e-icons' tooltipText='Pan Tool' cssClass='tb-item-start pan-item' />
                                    <ItemDirective prefixIcon='e-mouse-pointer e-icons' tooltipText='Select Tool' cssClass='tb-item-middle tb-item-selected' />
                                    <ItemDirective type='Separator' />
                                    <ItemDirective cssClass='tb-item-end tb-zoom-dropdown-btn' align='Right'
                                        template={() => <DropDownButtonComponent id="btnZoomIncrement"
                                            items={zoomMenuItems} content={Math.round(diagram.scrollSettings.currentZoom! * 100) + ' %'} select={zoomChange}
                                        ></DropDownButtonComponent>}
                                    />
                                </ItemsDirective>
                            </ToolbarComponent>
                        </div>
                    </div>
                    <div className="sb-mobile-palette-bar">
                        <div id="palette-icon" role="button" className="e-ddb-icons1 e-toggle-palette"></div>
                    </div>
                    <div id="palette-space" className="sb-mobile-palette">
                        <SymbolPaletteComponent
                            id="symbolpalette"
                            expandMode="Multiple"
                            palettes={palettes}
                            width="100%"
                            height="900px"
                            symbolHeight={60}
                            symbolWidth={60}
                            symbolMargin={{ left: 15, right: 15, top: 15, bottom: 15 }}
                            getNodeDefaults={getSymbolDefaults}
                            getSymbolInfo={getSymbolInfo}
                        />
                    </div>
                    <div id="diagram-space" className="sb-mobile-diagram">
                        <DiagramComponent
                            ref={diagramObj => diagram = diagramObj as DiagramComponent}
                            id="diagram"
                            width="100%"
                            height="900px"
                            rulerSettings={{ showRulers: true }}
                            tool={DiagramTools.Default}
                            snapSettings={{ horizontalGridlines: gridlines, verticalGridlines: gridlines }}
                            scrollSettings={{ scrollLimit: 'Infinity' }}
                            layout={{
                                type: 'Flowchart',
                                orientation: 'TopToBottom',
                                flowchartLayoutSettings: {
                                    yesBranchDirection: 'LeftInFlow',
                                    noBranchDirection: 'RightInFlow',
                                    yesBranchValues: ['Yes', 'True'],
                                    noBranchValues: ['No', 'False']
                                },
                                verticalSpacing: 50,
                                horizontalSpacing: 50
                            } as any}
                            dataSourceSettings={{
                                id: 'id',
                                parentId: 'parentId',
                                dataManager: new DataManager(flowchartData)
                            }}
                            scrollChange={(args: IScrollChangeEventArgs) => {
                                if (args.panState !== 'Start') {
                                    let zoomCurrentValue: any = (document.getElementById("btnZoomIncrement") as any).ej2_instances[0];
                                    zoomCurrentValue.content = Math.round(diagram.scrollSettings.currentZoom! * 100) + ' %';
                                }
                            }}
                            getNodeDefaults={(node: NodeModel): NodeModel => {
                                if (node.width === undefined) {
                                    node.width = 150;
                                    node.height = 50;
                                }
                                if ((node.shape as FlowShapeModel).type === 'Flow' && (node.shape as FlowShapeModel).shape === 'Decision') {
                                    node.width = 120;
                                    node.height = 100;
                                }
                                return node;
                            }}
                            getConnectorDefaults={(connector: Connector): ConnectorModel => {
                                connector.type = 'Orthogonal';
                                if (connector.annotations && connector.annotations.length > 0) {
                                    (connector.annotations as PathAnnotationModel[])[0]!.style!.fill = 'white';
                                }
                                return connector;
                            }}
                            dragEnter={dragEnter}
                        >
                            <Inject services={[DataBinding, PrintAndExport, FlowchartLayout]} />
                        </DiagramComponent>
                    </div>
                </div>
                <div id='dialog-container'>
                    <DialogComponent
                        ref={dialogObj => dialog = dialogObj as DialogComponent}
                        id='dialog'
                        header='<span class="e-icons e-assistview-icon" style="color: black;width:20px; font-size: 16px;"></span> AI Assist'
                        showCloseIcon={true}
                        isModal={true}
                        content={dialogContent}
                        target={document.getElementById('control-section') as HTMLElement}
                        width='540px'
                        visible={false}
                        height='310px'
                    />
                </div>
                <FabComponent id="ai-assist"
                    isPrimary={true} content='AI Assist' iconCss='e-icons e-assistview-icon'
                    onClick={() => { dialog.show(); }}
                ></FabComponent>

                {/* Loading indicator container */}
                <div id="loadingContainer" className="loading-container">
                    <div className="loading-indicator"></div>
                    <div className="loading-text">Generating Flowchart...</div>
                </div>
            </div>
        </>
    )
}

export default SmartFlowchart

// angular/src/app/diagram/smart-flowchart/smart-flowchart.component.ts
import { Component, ViewChild } from '@angular/core';
import {
  DiagramComponent, DiagramModule, NodeModel, ConnectorModel, SymbolPaletteModule, GridlinesModel, IScrollChangeEventArgs, IDragEnterEventArgs,
  PaletteModel, FileFormats, Connector, IExportOptions, FlowShapeModel, Node, DiagramTools, PathAnnotationModel, DataBindingService, PrintAndExportService, FlowchartLayoutService
} from '@syncfusion/ej2-angular-diagrams';
import { ToolbarModule, ClickEventArgs } from '@syncfusion/ej2-angular-navigations';
import { TextBoxComponent, TextBoxModule } from '@syncfusion/ej2-angular-inputs';
import { ButtonComponent, ButtonModule, FabModule } from '@syncfusion/ej2-angular-buttons';
import { UploaderModule, InputEventArgs } from '@syncfusion/ej2-angular-inputs';
import { DialogComponent, DialogModule } from '@syncfusion/ej2-angular-popups';
import { DropDownButtonComponent, DropDownButtonModule, MenuEventArgs } from '@syncfusion/ej2-angular-splitbuttons';
import { DataManager } from '@syncfusion/ej2-data';
import { flowchartData, flowShapes, exportItems, zoomMenuItems, connectorSymbols } from './datasource';
import { convertTextToFlowchart } from './ai-flowchart';
@Component({
  selector: 'app-smart-flowchart',
  standalone: true,
  imports: [DiagramModule, SymbolPaletteModule, ToolbarModule, ButtonModule, FabModule, UploaderModule, DialogModule, DropDownButtonModule, TextBoxModule],
  providers: [DataBindingService, PrintAndExportService, FlowchartLayoutService],
  templateUrl: './smart-flowchart.component.html',
  styleUrl: './smart-flowchart.component.css'
})
export class SmartFlowchartComponent {
  @ViewChild('diagram', { static: true }) public diagram!: DiagramComponent;
  @ViewChild('dialog', { static: true }) public dialog!: DialogComponent;
  @ViewChild('msgBtn1', { static: true }) public msgBtn1!: ButtonComponent;
  @ViewChild('msgBtn2', { static: true }) public msgBtn2!: ButtonComponent;
  @ViewChild('msgBtn3', { static: true }) public msgBtn3!: ButtonComponent;
  @ViewChild('textBox', { static: true }) public textBox!: TextBoxComponent;
  @ViewChild('sendButton', { static: true }) public sendButton!: ButtonComponent;
  public dataManager = new DataManager(flowchartData);
  public asyncSettings: Object = {
    saveUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Save',
    removeUrl: 'https://services.syncfusion.com/js/production/api/FileUploader/Remove'
  };
  public palettes: PaletteModel[] = [
    { id: 'flow', expanded: true, symbols: flowShapes, iconCss: 'e-ddb-icons e-flow', title: 'Flow Shapes' },
    { id: 'connectors', expanded: true, symbols: connectorSymbols, iconCss: 'e-ddb-icons e-connector', title: 'Connectors' }
  ];
  public zoomMenuItems: any = zoomMenuItems;
  public exportItems: any = exportItems;
  public gridlines: GridlinesModel = {
    lineColor: '#e0e0e0',
    lineIntervals: [
      1, 9, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75, 0.25, 9.75
    ]
  };
  public zoomContent: any;
  public diagramTools: any = DiagramTools;

  public getNodeDefaults(node: NodeModel): NodeModel {
    if (node.width === undefined) {
      node.width = 150;
      node.height = 50;
    }
    if ((node.shape as FlowShapeModel).type === 'Flow' && (node.shape as FlowShapeModel).shape === 'Decision') {
      node.width = 120;
      node.height = 100;
    }
    return node;
  }
  public getConnectorDefaults(connector: Connector): ConnectorModel {
    connector.type = 'Orthogonal';
    if (connector.annotations && connector.annotations.length > 0) {
      (connector.annotations as PathAnnotationModel[])[0]!.style!.fill = 'white';
    }
    return connector;
  }

  ngOnInit(): void {
    document.addEventListener('keypress', (event) => {
      if (event.key === 'Enter' && document.activeElement === (this.textBox as any).element.nativeElement) {
        if ((this.textBox as any).value !== '') {
          (this.dialog as any).hide();
          convertTextToFlowchart((this.textBox as any).value, this.diagram);
        }
      }
    });
    this.zoomContent = Math.round(this.diagram.scrollSettings.currentZoom! * 100) + ' %'
  }

  // Handles drag enter events
  public dragEnter(args: IDragEnterEventArgs): void {
    let obj: NodeModel = args.element as NodeModel;
    if (obj instanceof Node) {
      let ratio: number = 100 / obj.width;
      obj.width = 100;
      obj.height *= ratio;
      obj.offsetX += (obj.width - obj.width) / 2;
      obj.offsetY += (obj.height - obj.height) / 2;
      obj.style = { fill: '#357BD2', strokeColor: 'white' };
    }
  }

  showDialog() {
    this.dialog.show();
  }

  onSendClick() {
    this.dialog.hide();
    convertTextToFlowchart((this.textBox as any).value, this.diagram);
  }

  onBtnClick(msg: any) {
    this.dialog.hide();
    convertTextToFlowchart(msg, this.diagram);
  }

  onScrollChange(args: IScrollChangeEventArgs) {
    if (args.panState !== 'Start') {
      let zoomCurrentValue: any = (document.getElementById("btnZoomIncrement") as any).ej2_instances[0];
      zoomCurrentValue.content = Math.round(this.diagram.scrollSettings.currentZoom! * 100) + ' %';
    }
  }

  // Returns symbol defaults
  public getSymbolDefaults(symbol: NodeModel): void {
    const wideSymbols = new Set(['Terminator', 'Process', 'Delay']);
    const mediumSymbols = new Set(['Decision', 'Document', 'PreDefinedProcess', 'PaperTap', 'DirectData', 'MultiDocument', 'Data']);

    symbol.style = { strokeColor: '#757575' };

    if (wideSymbols.has((symbol as Node).id)) {
      symbol.width = 80;
      symbol.height = 40;
    } else if (mediumSymbols.has((symbol as Node).id)) {
      symbol.width = 50;
      symbol.height = 40;
    } else {
      symbol.width = 50;
      symbol.height = 50;
    }
  }

  public getSymbolInfo(): { fit: boolean } {
    return { fit: true };
  }

  // Export and print logic
  public printDiagram(): void {
    let options: IExportOptions = {};
    options.mode = 'Download';
    options.region = 'Content';
    options.multiplePage = this.diagram.pageSettings.multiplePage;
    options.pageHeight = this.diagram.pageSettings.height;
    options.pageWidth = this.diagram.pageSettings.width;
    this.diagram.print(options);
  }

  // Toolbar actions
  public toolbarClick(args: ClickEventArgs): void {
    let item = args.item.tooltipText;
    switch (item) {
      case 'Select Tool':
        this.diagram.clearSelection();
        this.diagram.tool = DiagramTools.Default;
        break;
      case 'Pan Tool':
        this.diagram.clearSelection();
        this.diagram.tool = DiagramTools.ZoomPan;
        break;
      case 'New Diagram':
        this.diagram.clear();
        break;
      case 'Print Diagram':
        this.printDiagram();
        break;
      case 'Save Diagram':
        this.download(this.diagram.saveDiagram());
        break;
      case 'Open Diagram':
        (document.getElementsByClassName('e-file-select-wrap') as any)[0]
          .querySelector('button')
          .click();
        break;
    }
    this.diagram.dataBind();
  }

  // Zoom change handler
  public zoomChange(args: MenuEventArgs): void {
    const currentZoom = this.diagram.scrollSettings.currentZoom!;
    let zoomFactor: number;

    switch (args.item.text) {
      case 'Zoom In':
        this.diagram.zoomTo({ type: 'ZoomIn', zoomFactor: 0.2 });
        break;
      case 'Zoom Out':
        this.diagram.zoomTo({ type: 'ZoomOut', zoomFactor: 0.2 });
        break;
      case 'Zoom to Fit':
        zoomFactor = 1 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
      case 'Zoom to 50%':
        zoomFactor = 0.5 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
      case 'Zoom to 100%':
        zoomFactor = 1 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
      case 'Zoom to 200%':
        zoomFactor = 2 / currentZoom - 1;
        this.diagram.zoomTo({ zoomFactor });
        break;
    }

    const zoomCurrentValue: DropDownButtonComponent = (document.getElementById('btnZoomIncrement') as any).ej2_instances[0];
    if (this.diagram.scrollSettings.currentZoom)
      zoomCurrentValue.content = Math.round(this.diagram.scrollSettings.currentZoom * 100) + '%';
  }

  public onselectExport(args: MenuEventArgs): void {
    let exportOptions: IExportOptions = {
      format: args.item.text as FileFormats,
      mode: 'Download',
      region: 'PageSettings',
      fileName: 'Export',
      margin: { left: 0, top: 0, right: 0, bottom: 0 }
    };
    this.diagram.exportDiagram(exportOptions);
  }

  // Handle file upload success
  public onUploadSuccess(args: any): void {
    let reader = new FileReader();
    reader.readAsText(args.file.rawFile);
    reader.onloadend = (event: any) => {
      this.diagram.loadDiagram(event.target.result);
    };
  }

  // Download diagram as JSON
  public download(data: string): void {
    if ((window.navigator as any).msSaveBlob) {
      let blob: Blob = new Blob([data], { type: 'data:text/json;charset=utf-8,' });
      (window.navigator as any).msSaveOrOpenBlob(blob, 'Diagram.json');
    }
    else {
      let dataString = 'data:text/json;charset=utf-8,' + encodeURIComponent(data);
      let element = document.createElement('a');
      element.href = dataString;
      element.download = 'Diagram.json';
      document.body.appendChild(element);
      element.click();
      element.remove();
    }
  }

  // Handle textbox input change
  public onTextBoxChange(args: InputEventArgs) {
    if (args.value !== '') {
      this.sendButton.disabled = false;
    } else {
      this.sendButton.disabled = true;
    }
  }

}

<h4 style="text-align: center;">Text To Flow Chart</h4>
<div class="description-container e-card">
    <div class='e-card-content '>
        <p>
            This demo illustrates how the Angular Diagram Component, enhanced with AI, creates flowcharts with nodes and
            connectors. It visually represents processes, workflows, and decision paths, offering a clear and
            interactive way to map procedures.
        </p>
    </div>
</div>
<div class="container">
    <link href="https://ej2.syncfusion.com/javascript/demos/src/diagram/styles/diagram-common.css" rel="stylesheet" />

    <div class="main">
        <div class="diagram-upload-file">
            <ejs-uploader id="fileupload" name="UploadFiles" [asyncSettings]="asyncSettings"
                (success)="onUploadSuccess($event)" [showFileList]="false">
            </ejs-uploader>
        </div>
        <div class="db-toolbar-editor">
            <div class="db-toolbar-container">
                <ejs-toolbar id="toolbarEditor" [width]="'100%'" [height]="49" (clicked)="toolbarClick($event)">
                    <e-items>
                        <e-item prefixIcon="e-icons e-circle-add" tooltipText="New Diagram"></e-item>
                        <e-item prefixIcon="e-icons e-folder-open" tooltipText="Open Diagram"></e-item>
                        <e-item prefixIcon="e-icons e-save" tooltipText="Save Diagram"></e-item>
                        <e-item prefixIcon="e-icons e-print" tooltipText="Print Diagram"></e-item>
                        <e-item type="Input" tooltipText="Export Diagram">
                            <ng-template #template>
                                <button ejs-dropdownbutton id="exportBtn" [items]="exportItems"
                                    [iconCss]="'e-ddb-icons e-export'" (select)="onselectExport($event)">
                                </button>
                            </ng-template>
                        </e-item>
                        <e-item type="Separator"></e-item>
                        <e-item prefixIcon="e-icons e-pan" tooltipText="Pan Tool"
                            cssClass="tb-item-start pan-item"></e-item>
                        <e-item prefixIcon="e-icons e-mouse-pointer" tooltipText="Select Tool"
                            cssClass="tb-item-middle tb-item-selected"></e-item>
                        <e-item type="Separator"></e-item>
                        <e-item cssClass="tb-item-end tb-zoom-dropdown-btn" align="Right">
                            <ng-template #template>
                                <button ejs-dropdownbutton id="btnZoomIncrement" [items]="zoomMenuItems"
                                    [content]="zoomContent" (select)="zoomChange($event)">
                                </button>
                            </ng-template>
                        </e-item>
                    </e-items>
                </ejs-toolbar>
            </div>
        </div>
        <div class="sb-mobile-palette-bar">
            <div id="palette-icon" role="button" class="e-ddb-icons1 e-toggle-palette"></div>
        </div>
        <div style="margin-top: 5px;border-top: 0.5px solid #b0b0b0;" id="palette-space" class="sb-mobile-palette">
            <ejs-symbolpalette id="symbolpalette" [expandMode]="'Multiple'" [palettes]="palettes" [width]="'100%'"
                [height]="'900px'" [symbolHeight]="60" [symbolWidth]="60"
                [symbolMargin]="{ left: 15, right: 15, top: 15, bottom: 15 }" [getNodeDefaults]="getSymbolDefaults"
                [getSymbolInfo]="getSymbolInfo">
            </ejs-symbolpalette>
        </div>
        <div style="margin-top: 5px;border: 0.5px solid #b0b0b0;" id="diagram-space" class="sb-mobile-diagram">
            <ejs-diagram #diagram id="diagram" width="100%" height="900px" [rulerSettings]="{ showRulers: true }"
                [tool]="diagramTools" [snapSettings]="{ horizontalGridlines: gridlines, verticalGridlines: gridlines }"
                [scrollSettings]="{ scrollLimit: 'Infinity' }" [layout]="{
    type: 'Flowchart',
    orientation: 'TopToBottom',
    flowchartLayoutSettings: {
      yesBranchDirection: 'LeftInFlow',
      noBranchDirection: 'RightInFlow',
      yesBranchValues: ['Yes', 'True'],
      noBranchValues: ['No', 'False']
    },
    verticalSpacing: 50,
    horizontalSpacing: 50
  }" [dataSourceSettings]="{
    id: 'id',
    parentId: 'parentId',
    dataManager: dataManager
  }" (scrollChange)="onScrollChange($event)" [getNodeDefaults]="getNodeDefaults"
                [getConnectorDefaults]="getConnectorDefaults" (dragEnter)="dragEnter($event)">
            </ejs-diagram>
        </div>
    </div>
    <div id='container'>
        <ejs-dialog #dialog id='dialog' target='#container'
            header='<span class="e-icons e-assistview-icon" style="color: black;width:20px; font-size: 16px;"></span> AI Assist'
            showCloseIcon='true' isModal='true' [visible]='false' [width]="'540px'" [height]="'310px'">
            <p style="margin-bottom: 10px; font-weight: bold;">Suggested Prompts</p>

            <button ejs-button id="btn2" cssClass="e-primary" (click)="onBtnClick('Flowchart for online shopping')"
                style="flex: 1; overflow: visible; border-radius: 8px; margin-bottom: 10px">
                Flowchart for online shopping
            </button>

            <button ejs-button id="btn1" cssClass="e-primary"
                (click)="onBtnClick('Flowchart for Mobile banking registration')"
                style="flex: 1; overflow: visible; border-radius: 8px; margin-bottom: 10px">
                Flowchart for Mobile banking registration
            </button>

            <button ejs-button id="btn3" cssClass="e-primary" (click)="onBtnClick('Flowchart for Bus ticket booking')"
                style="flex: 1; overflow: visible; border-radius: 8px; margin-bottom: 10px">
                Flowchart for Bus ticket booking
            </button>

            <div style="display: flex; align-items: center; margin-top: 20px;">
                <ejs-textbox #textBox id="textBox" placeholder="Please enter your prompt here..." style="flex: 1;"
                    (input)="onTextBoxChange($event)"></ejs-textbox>

                <button ejs-button id="db-send" (click)="onSendClick()" iconCss='e-icons e-send' cssClass="e-primary"
                    style="margin-left: 5px; height: 32px; width: 32px;"></button>
            </div>
        </ejs-dialog>
    </div>
    <button ejs-fab id="ai-assist" [isPrimary]="true" content="AI Assist" iconCss="e-btn-icon e-icons e-assistview-icon e-icon-left"
        (click)="showDialog()"></button>

    <!-- Loading indicator container -->
    <div id="loadingContainer" class="loading-container">
        <div class="loading-indicator"></div>
        <div class="loading-text">Generating Flowchart...</div>
    </div>
</div>
